### PR TITLE
Added icons

### PR DESCRIPTION
**Pull request by Giannis05**
gr.cosmote.whatsup/gr.cosmote.whatsup.Activities.SplashScreenActivity
gr.cosmote.whatsup/gr.cosmote.whatsup.Activities.HomeActivity

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi! Congrats on your first contribution, the icon looks good, you only need to export it in white tho :)

**Comment by Donnnno** [comment]
Also can you provide the activity name with the right formatting? Check Turtl for how to do that: https://f-droid.org/en/packages/org.xphnx.iconsubmit/

**Comment by Giannis05** [comment]
Yes, I'm sorry. I used adb to find the activity name. The Turtl app gave me this:


<item component="ComponentInfo{gr.cosmote.whatsup/gr.cosmote.whatsup.Activities.SplashScreenActivity}" drawable="whatsup"/>

Is it correct?

**Comment by Giannis05** [comment]
Yes, I'm sorry. I used adb to find the activity name. The Turtl app gave me this:


<item component="ComponentInfo{gr.cosmote.whatsup/gr.cosmote.whatsup.Activities.SplashScreenActivity}" drawable="whatsup"/>

Is it correct?

**Comment by Giannis05** [comment]
Yes I'm sorry. I used adb to find the activity name. The Turtl app gave me this:
```
<!-- What's Up -->
<item component="ComponentInfo{gr.cosmote.whatsup/gr.cosmote.whatsup.Activities.SplashScreenActivity}" drawable="whatsup"/>
```
Is it correct?

**Comment by Donnnno** [comment]
Yes! Thank you :)

**Comment by Donnnno** [comment]
I removed the box so the main shape can be bigger: 
image

**Pull request merged**
