### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by ktutsch**
Icons

### CODE REVIEW

**Comment by Donnnno** [comment]
What does the F-droid check do?

**Comment by Donnnno** [comment]
> Icons

Lots of em!

**Comment by ktutsch** [comment]
> What does the F-droid check do?

It gets all https://f-droid.org links from the file in the first argument and checks if they return a 404 error or if they exist. Existing links get printed.

**Comment by Donnnno** [comment]
Oh that's pretty cool!

**Pull request merged**
