### PR TITLE
Arcicons day night

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Might need some new launcher icon and some other graphical changes

### CODE REVIEW

**Comment by Donnnno** [comment]
This is sick, gonna take a good look at everything later!

It was on my to-do list for a while, but you've beat me to it 😅 great work!!!

**Comment by Donnnno** [comment]
All the drawables are added to gitignore, why exactly?

**Comment by Kaiserdragon2** [comment]
These are recreated at build time from the svgs at each build.

**Comment by Donnnno** [comment]
oh that's awesome!

**Comment by Donnnno** [comment]
Just tested it, and wow the android studio icon generation is awesome!

The icon pack is very cool like that too, although some launchers have trouble with changing it so quickly (or it's just my Samsung phone)

I've removed the Google Play build option because Google would definitely remove the apps again, if I'm gonna release that version there 😅 

Also gonna have to create some graphics soon :)



Fantastic work :)))

**Comment by Donnnno** [comment]
Todo:

- [ ] Store listings
- [ ] Graphics
- [ ] app icon
- [ ] Theming tweaks?

**Comment by Donnnno** [comment]
Noticed that all the You drawables are removed, just to be sure, does it generate the clock and widgets as well?

**Comment by Donnnno** [comment]
Hoping to merge this before the holidays, btw!

**Comment by Donnnno** [comment]
I think we're ready :)

**Pull request merged**
