### PR TITLE
Vector drawable example

### LINKED ISSUE #16: PNG icons?
I see the icons are in PNG format with different sizes for each dpi.
1. Can't we use vector drawables? It would make the app a lot smaller and also scale indefinitely.
2. There is also the possibility to adding [AdaptiveIconDrawable](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable) for API level 26 and above

What do you think?

### PR DESCRIPTION
**Pull request by TBog**
This is an example to fix #16 for the calculator icon
Steps:
1. Set project grouping to "Android"  
image

2. Right click on calculator and `New` > `Vector Asset`
image

3. Configure vector asset:
  * Asset Type: **Local file**
  * Name: **calculator**
  * Path: path to **Arcticons/icons/calculator.svg**
  * Size: 48dp x 48dp
image

4. Press **Next** and confirm path 
image

5. Now you should have 6 calculator entries 
image

6. Delete all `calculator.png` files 
image

### CODE REVIEW

**Comment by Donnnno** [comment]
Okay cool, but is it possible to do a whole batch like this?

**Comment by Donnnno** [comment]
Also, right now it seems to break the iconlist :s

image

**Comment by TBog** [comment]
> Also, right now it seems to break the iconlist :s

fixed in PR #20

**Comment by TBog** [comment]
This PR also adds the Samsung calculator with the 'calculator' drawable

**Comment by TBog** [comment]
> Okay cool, but is it possible to do a whole batch like this?

I found [this](https://github.com/ravibhojwani86/Svg2VectorAndroid) project but can't test right now

**Comment by Donnnno** [comment]
I think the world isn't ready for xml icons yet, I tested it, replaced all icons with xml's, and it crashes the app almost immediately

**Comment by TBog** [comment]
> I've created a xml brach, you can view it there.

I can't find the branch. Maybe you forgot to push it to GitHub?

**Comment by Donnnno** [comment]
https://github.com/Donnnno/Arcticons/tree/xml_icons 
Can you view this?

**Comment by TBog** [comment]
> https://github.com/Donnnno/Arcticons/tree/xml_icons
> Can you view this?

I see `xml_icons` and `main` point to the same commit
see https://github.com/Donnnno/Arcticons/network

**Comment by Donnnno** [comment]
Oops, forgot to push it. Changing it now

**Comment by TBog** [comment]
I think it crashes because the icons used in the main app buttons are accessed as if they are bitmaps. You can skip those or we can fix the way the code displays them.

**Comment by TBog** [comment]
You changed the names of the drawables by adding `_svg` at the end. This causes the crash!

**Comment by Donnnno** [comment]
oh haha sorry, changed it. gonna test it now

**Comment by Donnnno** [comment]
The icons now work in the launcher but not in the app icon list

**Comment by Donnnno** [comment]
Also can we change the `ic_code.xml` location and `ic_favorite.xml` to another folder?

**Comment by TBog** [comment]
`lettera` not found
`letterb` not found
`letterc` not found
`letterd` not found
`lettere` not found
`letterf` not found
`letterg` not found
`letterh` not found
`letteri` not found
`letterj` not found
`letterk` not found
`letterl` not found
`letterm` not found
`lettern` not found
`lettero` not found
`letterp` not found
`letterq` not found
`letterr` not found
`letters` not found
`lettert` not found
`letteru` not found
`letterv` not found
`letterw` not found
`letterx` not found
`lettery` not found
`letterz` not found
`number0` not found
`number1` not found
`number2` not found
`number3` not found
`number4` not found
`number5` not found
`number6` not found
`number7` not found
`number8` not found
`number9` not found

**Comment by Donnnno** [comment]
Hmmm... Maybe a svg > xml conversion error? 


image
image
image

**Comment by TBog** [comment]
> Hmmm... Maybe a svg > xml conversion error?

If you see a conversion error please try to use the steps I provided at the top for the icon with the problem.
Maybe Android Studio has a better conversion than `svg2vectorandroid`

**Comment by Donnnno** [comment]
The missing letters and numers error is fixed by sorting the xml's

**Comment by Donnnno** [comment]
> If you see a conversion error please try to use the steps I provided at the top for the icon with the problem.

I'll try that later today, gotta go back to work for now :)

**Comment by TBog** [comment]
I found and used [svgo](https://github.com/svg/svgo) to optimize my SVG files before importing with Android Studio. I think if you add this step before running [Svg2VectorAndroid](https://github.com/ravibhojwani86/Svg2VectorAndroid) it will fix the conversion errors.

**Comment by Donnnno** [comment]
Hey, thanks! SVGo works great! I just tested it. Unfortunately, the errors still persist with that method. I just made a test build on my phone with the XML icons, but it works really slow right now. Any idea how that could happen?

**Comment by TBog** [comment]
SVGs are drawing commands, when loaded by the phone it generates the bitmap for the dpi you have. If the bitmap is not cached it will generate it again.

Can you test it with my launcher? I have an option to enable/disable the cache. Could you please test with and without cache and report back?

**Comment by TBog** [comment]
Could you please push the changes to a branch so a can have a look at it sometime next week?

**Comment by Donnnno** [comment]
Yeah, sorry I was talking about the grid in the icon pack, I noticed it gets faster after a while.

As for the SVG's, it might have something to do with points that are too close to each other or something.

**Comment by TBog** [comment]
> As for the SVG's, it might have something to do with points that are too close to each other or something.

1. Is the issue always with the same icons? Does it change in any way if you scroll slow/fast before the icon bitmap gets generated? 
2. I know SVGo has some parameters that should change the precision of the SVG points, it's worth investigating.

**Comment by TBog** [comment]
Found the problem. Svg2VectorAndroid uses an older version of Android Studio tools. I got [PR 8](https://github.com/ravibhojwani86/Svg2VectorAndroid/pull/8) and compiled it myself using `./gradlew fatJar` and used the resulting `Svg2VectorAndroid-1.0.2.jar`. Now the xml is no longer corrupted.

**Comment by Donnnno** [comment]
Oh, great! Just looked at your other pull request, and it works! 
Can you send me the Svg2VectorAndroid files so that I can use it too?

**Comment by TBog** [comment]
I don't have access to my PC atm. 
There is a jar in the PR I linked. I've not tested it but it should be the same.

It's easy to clone the PR and run the gradle build to generate the jar.

**Comment by TBog** [comment]
[here](https://github.com/TBog/Svg2VectorAndroid/blob/jar1.0.2/Svg2VectorAndroid-1.0.2.jar) is the updated Svg2VectorAndroid

**Comment by Donnnno** [comment]
Thank you! If everything works right 1.5 probably has vector icons then.
The only thing  that's weird now is that loading the icons for the first time (in the grid) is really lagging.

**Comment by TBog** [comment]
> The only thing  that's weird now is that loading the icons for the first time (in the grid) is really lagging.

What phone are you testing with? 
I'll try to make a new PR with some icons loading from the beginning, I think it will help. 
I think my phone is too fast for me to notice.

**Comment by Donnnno** [comment]
I'm using a xiaomi mi a1 right now. It's a 3+ years old budget phone. So it's not weird that it gets slow sometime, but I'e never encountered the lag with the png's.

Still I'm all for the xml icons, it's way easier than exporting 5 different sizes :)

**Comment by Donnnno** [comment]
Oh no, we may have another problem. I just tested the icon pack with Open Launher to look at another issue. 
And it looks like this:



Idk if this is just me but if only a few selected launchers are compatible with xml icons it wont make much sense to switch.

**Comment by TBog** [comment]
> Idk if this is just me but if only a few selected launchers are compatible with xml icons it wont make much sense to switch.

Maybe we should open an issue with Open Launcher. It's something that should work. But it's your icon pack and your decision.

**Comment by Donnnno** [comment]
I have almost no knowledge of Android, but could it be something with the api level?

_Android 5.0 (API level 21) was the first version to officially support vector drawables with `VectorDrawable `and `AnimatedVectorDrawable`, but you can support older versions with the Android support library, which provides the `VectorDrawableCompat `and `AnimatedVectorDrawableCompat `classes._ 

from: https://developer.android.com/guide/topics/graphics/vector-drawable-resources

**Comment by TBog** [comment]
What device did you use for your test?

**Comment by Donnnno** [comment]
Your launcher displays them right!
I'm just worried about open-launcher because it's one of the most common f-droid launchers.

**Comment by TBog** [comment]
> I'm just worried about open-launcher because it's one of the most common f-droid launchers.

Open an issue with them and post the link here and I'll try to either make a PR to fix it for them or show them the relevant code I use in my launcher.

**Pull request closed without merging**
