### PR TITLE
Add M&T Bank

### PR DESCRIPTION
**Pull request by Saijin-Naib**
Who knows how many folks use this

### CODE REVIEW

**Comment by Donnnno** [comment]
Hey, It seems like you used the .TTF font, but that one isn't compatible with the icons, you should use the .svg and place each letter manually.

Because they are only words, I'll do it for these, but in the future it would be great if you can use the SVG font :-)

https://github.com/Donnnno/Arcticons/blob/main/templates/arcticons_font.svg

**Comment by Saijin-Naib** [comment]
Hmm, okay, thanks.

How do I keep the alignment and kerning consistent if I'm placing the letters manually?

**Comment by Donnnno** [comment]
_with feeling_

**Comment by Saijin-Naib** [comment]
This is going to be a disaster :rofl:

**Comment by Donnnno** [comment]
> _with feeling_

To give a bit more context, kerning is a tedious hard thing to get right, and at the end it's all about feeling

https://method.ac/type/

**Comment by Donnnno** [comment]
Also, the icons:

image

**Pull request closed without merging**
