### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by Rhodney**
Icons for 99, Adobe Comp, Adobe Photoshop Fix, Adobe Photoshop Mix, ArduinoDroid, Avira Phantom VPN and what3words.
appfilter.xml was updated too.

com.taxis99/com.didi.sdk.app.DidiLoadDexActivity
com.adobe.comp/com.adobe.comp.activities.SplashScreenActivity
com.adobe.adobephotoshopfix/com.adobe.adobephotoshopfix.FCSplashScreenActivity
com.adobe.photoshopmix/com.adobe.photoshopmix.SplashScreenActivity
name.antonsmirnov.android.arduinodroid2/name.antonsmirnov.android.arduinodroid.ui.OnboardingActivity
com.avira.vpn/com.avira.vpn.MainActivity
com.what3words.android/com.what3words.android.ui.splash.SplashActivity

**Icons Preview:**
https://i.ibb.co/mThzGQz/Icons-Preview.png

### CODE REVIEW

**Comment by Donnnno** [comment]
Cool! They look excellent!

**Comment by Rhodney** [comment]
Thanks. I will upload some more icons soon from popular apps that I use. After that I will try to help with other users requests and more downloaded apps from PlayStore/F-Droid. If I deviate a little from the art that the project proposes or some icon is not good enough, please let me know.

**Comment by Rhodney** [comment]
Preview of the second set. iFood icon already exist in appfilter.xml, but the image did not exist in the project folders.

https://www.imagemhost.com.br/images/2021/02/26/Preview.png

**Comment by Rhodney** [comment]
com.box.android/com.box.android.activities.login.SplashScreenActivity
com.cabify.rider/com.cabify.rider.presentation.splash.SplashActivity
com.google.android.apps.wellbeing/com.google.android.apps.wellbeing.settings.LauncherActivity
com.evernote/com.evernote.ui.HomeActivity
com.google.android.apps.meetings/com.google.android.apps.meetings.splash.SplashActivity
com.ParallelSpace.Cerberus/com.google.firebase.MessagingUnityPlayerActivity
br.com.brainweb.ifood/br.com.brainweb.ifood.mvp.splash.view.SplashScreenActivity
com.microsoft.microsoftsolitairecollection/com.smokingguninc.engine.framework.SgiLauncherActivity
com.oneplus.contacts/com.oneplus.contacts.activities.OPPeopleActivity
com.oneplus.filemanager/com.oneplus.filemanager.HomePageActivity
com.miniclip.plagueinc/com.miniclip.plagueinc.SplashActivity
com.grability.rappi/com.grability.app.splash.SplashActivity
com.stremio.one/com.stremio.MainActivity
com.google.android.apps.youtube.music/com.google.android.apps.youtube.music.activities.MusicActivity

**Comment by Donnnno** [comment]
Thanks for all the icons, they look very good!
A couple of feedback points for the future:
- While creating my icons I noticed that outline letters were very messy and hard to read in a big list, I've created a line-based font as a solution, you can find it in the templates folder.
- A technical thing: the filename of an icon can't start with a number or can't contain a dash or something like that.

But overall, they look very professional, I've done some sizing adjustments and changed the ifood icon to make it more consistent with the rest.

A preview of the ifood icon with the font:
image

**Pull request merged**
