### PR TITLE
Added 11 Icons Some Updated!

### PR DESCRIPTION
**Pull request by xprateek**
### **Update 11 Icons**
Group 1

1. AyuGram
2. BCR (Foss App)
3. BCR GUI (Foss App)
4. Find My Device (Update New icon)
5. Google Fit (Update New icon)
6. Kotak 811 Bank
7. Google Lens (Update New icon)
8. MRepo (Foss App)
9. OnePlus Health
10. Google Reading Mode
11. X Corp (Twitter --> X)

Drafted PR Commit! by @xprateek

### CODE REVIEW

**Comment by xprateek** [comment]
**
Some Icons not looks good sadly 😕 

(BCR icons overly strokes lines, same with reading mode app)
**
@Donnnno

**Comment by Donnnno** [comment]
image
 made some adjustments! 

Keeping the dead bird as twitter icon because fuck elon, but the X is already in there, you can apply it manually :)

**Comment by xprateek** [comment]
You are just amazing 💯 will update more & more icons!

**Comment by Fptbb** [comment]
Please revert X (Twitter) logo to the real logo, now the new one, it's fun as a joke and protest but having a dead bird icon as a main using a launcher like Samsung's is a troublesome problem, and a flaw on the integrity of the app, as it is supposed to default real logos, not the optional alternatives.

**Comment by Donnnno** [comment]
Hi @Fptbb ! I understand your concern about the icon. At this time I don't have any plans to change it. The goal of Arcticons is to provide clean looking icons, but we're artists and our own interpretations of how an icon should look. I personally think the X logo and everything Musk does is garbage, so I chose to use the dead bird instead (it's kinda metaphorically at this point). 
I'd suggest using a third party launcher like Nova if you want to see the X. But who knows, maybe I'll become tired of it one day.

Also Mastodon is a perfect alternative, with a much better icon :-)

**Comment by Donnnno** [comment]
Oops I accidentally deleted the last comment because GitHub showed it double for me.

**Pull request merged**
