### PR TITLE
Added icon

### PR DESCRIPTION
**Pull request by Giannis05**
image

### CODE REVIEW

**Comment by Donnnno** [comment]
Looks good!

**Comment by coxackie** [comment]
isn't this the same as the Adguard icon? They are indeed very similar as original icons anyway - YASNAC is "white background and green tick" while Adguard is "green background and white tick". What could differentiate them as Arcticons?

**Comment by SolarisSonne** [comment]
[icons.zip](https://github.com/Donnnno/Arcticons/files/7975331/icons.zip)

**Comment by SolarisSonne** [comment]
my first try, i hope it fits

**Comment by Donnnno** [comment]
Not the right place @SolarisSonne ! You need to create your own pull request :)

**Pull request merged**
