### PR TITLE
Pocketbook icon

### PR DESCRIPTION
**Pull request by onuronsekiz**
Corrected wrong app icon, deleted duplicate_1

### CODE REVIEW

**Comment by Donnnno** [comment]
was in the middle of preparing the update, so I've changed it there! Thanks for the heads up :)

**Comment by onuronsekiz** [comment]
wow, so an update is really coming,
I can finally delete tons of apps that I would never use.
Btw, would f-droid update come late again?

**Comment by Donnnno** [comment]
Yes, everything is ready, but want to make sure everything is good!
If you have android studio, you should be able to test the new version already. :-) 

F-Droid usually takes a couple of days, yea.

**Comment by Donnnno** [comment]
550 new icons and 8068 in total btw, fantastic work!

**Pull request closed without merging**
