### PR TITLE
40 new icons

### PR DESCRIPTION
**Pull request by onuronsekiz**
40 new icons. (*1 has same icon)
1 previous icon revised.

Uploaded:

1. Afet Acil Arama
2. Antalya Kart
3. Bimcell
4. CEPTETEB
5. CK Enerji
6. e-Adalet
7. e-Arabulucu
8. E-Bilet
9. e-Bilirkişi
10. e-Duruşma
11. e-Okul Öğretmen
12. E-okul Vbs (*)
13. eAfad
14. EBA
15. EBA Akademik Destek
16. ebebek
17. Emacs
18. Enerjisa Mobil
19. etstur
20. Evidea
21. Fibabanka
22. GiB
23. Hayhay
24. Juzdan
25. MANGO
26. Mavi
27. MediaMarkt
28. Meteoroloji
29. Ptt Bank
30. Şeker Mobil
31. Tatilbudur
32. Teamspeak
33. Tracker Detect
34. UPTION
35. Uyap Doküman Editör
36. UYAP Mevzuat
37. Uyap Mobil
38. Vatan
39. Watsons
40. Zipcar Türkiye
41. Zorlu Enerji

Revised:

1. Bim

### CODE REVIEW

**Review by onuronsekiz — COMMENTED** [review]
Tracker Detect icon

**Comment by Donnnno** [comment]
Amazing work! Will add everything soon!

**Comment by onuronsekiz** [comment]
Thanks,
My fascination to your work encourages me to improve it.
Your appreciation is excites me to collaborate even more.

**Comment by Donnnno** [comment]
That's fantastic to hear! With your efforts, we're getting to the 8K icons in no time 😆 

Oh and btw, if you want feedback or talk with the other contributors, we're on Matrix/Element: https://matrix.to/#/#arcticons-central:matrix.org

**Pull request merged**
