### PR TITLE
Added Sram AXS, OpenSCQ30 icons

### PR DESCRIPTION
**Pull request by KR4U7H3R**
Added Sram AXS and OpenSCQ30 icons. Updated one icon.

I edited appfilter.xml in the browser. It seems to have redone the whole file. No idea why... I just added the last two entries.

Regards

### CODE REVIEW

**Comment by Donnnno** [comment]
Hey, looks like you edited the appfilter with a `LF` editor, can you set it to` CRLF`? a powerful editor like VSCode could do that for you.

**Comment by Donnnno** [comment]
What's wrong with the current  Filmstars icon?

**Comment by KR4U7H3R** [comment]
The arrow is slightly off. Should be better now.

**Comment by Donnnno** [comment]
cool

**Pull request merged**
