### PR TITLE
Improve IconActivity

### PR DESCRIPTION
**Pull request by TBog**
This PR will make a grid layout for IconActivity

* This will fix the vector loading and allow dynamic number of columns in the grid.
* You can change the size of the icons from `dimens.xml` > `icon_preview_size` right now it's 48dp
* The icons are loading when needed, not like before where all got loaded at the start
* ~~The decoding of the icon resource is done by the ImageView when calling `icon.setImageResource(resId);`~~ 
* The icon decoding is done asynchronously off the UI thread. A Drawable is returned on the UI thread to be associated with the ImageView. 

If you need any tweaks please leave a comment.

### CODE REVIEW

**Comment by Donnnno** [comment]
I'll take a look at it, thanks!

**Comment by Donnnno** [comment]
Wow, that works great, way less laggy than before haha. 

I have only two things to that come to my mind right now: 
- Can you change the background to black?
- Maybe a long press icon name thing would be nice to have, but not necessary 

Thanks!

**Comment by TBog** [comment]
> - Can you change the background to black?
This can be done from the xml layout easily 

> - Maybe a long press icon name thing would be nice to have, but not necessary 
I wanted to add it but I was not sure if you desired it as it was not implemented. Is a [Toast](https://developer.android.com/guide/topics/ui/notifiers/toasts) enough? It should display the drawable name, right?

**Comment by Donnnno** [comment]
> Is a Toast enough?

Yes, that was exactly what I was thinking about!

**Comment by TBog** [comment]
* We can also share the image if you think that would be useful.
  * We could also implement a content resolver so requests for images could show this app

**Comment by Donnnno** [comment]
> We can also share the image if you think that would be useful

Useful for what exactly? 

> We could also implement a content resolver so requests for images could show this app

Do you mean like an icon request button or something?

**Comment by TBog** [comment]
> > We can also share the image if you think that would be useful
> 
> Useful for what exactly? 

Share the icon to WhatsApp or Snapseed 

> > We could also implement a content resolver so requests for images could show this app
> 
> Do you mean like an icon request button or something? 

When another app requests an image, like the browser when you press Choose Image on a website

**Comment by Donnnno** [comment]
Ah okey, I think we don't need a share button for the icons. The second thing could be a nice to have but also not necessary :^)

**Comment by Donnnno** [comment]
Looks great! Is it ready to merge?

**Comment by TBog** [comment]
> Looks great! Is it ready to merge?

It's ready to merge.

**Comment by Donnnno** [comment]
Cool! thanks :)

**Pull request merged**
