### PR TITLE
Adding ksync and park4night

### PR DESCRIPTION
**Pull request by fanfu**

### CODE REVIEW

**Comment by fanfu** [comment]
@Donnnno I may have done a mistake somewhere since this PR also includes changes that were part of PR #309 
I'm not really comfortable with git. Hope this will not make your task more difficult

**Comment by Donnnno** [comment]
No worries, I think it's an easy fix :)

**Comment by Donnnno** [comment]
Can you edit the appfilter in /other the next time? (it a new thing)

**Comment by fanfu** [comment]
Sure I will. Thanks for your implication on this project

**Pull request merged**
