### PR TITLE
#306 sans appfilter.xml

### PR DESCRIPTION
**Pull request by Aman9das**
Add 5 icons

### CODE REVIEW

**Comment by Donnnno** [comment]
I wasn't able to check this one out before merging, but there are some really weird things happening in here...
For example, these huge canvases
image

**Comment by Donnnno** [comment]
Also, I can't open heavymetal, library or scrobb with inkscape or illustrator.

**Comment by Donnnno** [comment]
The icons that I can open do look very good tho :^)

**Comment by Aman9das** [comment]
OK delete them I'll fix it and add again

**Comment by Donnnno** [comment]
Cool! Thanks, maybe something went wrong with exporting? 
Github marks this in the diff: 
image

**Comment by Aman9das** [comment]
Oh yes

**Pull request merged**
