### PR TITLE
belote and 6 more icons

### PR DESCRIPTION
**Pull request by aloxe**

### CODE REVIEW

**Comment by aloxe** [comment]
@Donnnno ekonto app has been renamed. I removed all reference in src but I am not sure this is how we remove the old icon. Just tell me.

**Comment by Donnnno** [comment]
Hi I can remove those, can you undo these changes? 

Those files are generated upon every release :) 

image

**Comment by aloxe** [comment]
Undid changes related to ekonto removal, also minified svg

**Comment by Donnnno** [comment]
Great ! Thank you!

**Pull request merged**
