### PR TITLE
added app

### PR DESCRIPTION
**Pull request by basings**
added symfonium

### CODE REVIEW

**Review by basings — COMMENTED** [review]
something went wrong here

**Comment by basings** [comment]
<item component="ComponentInfo{app.symfonik.music.player/app.symfonik.ui.MainActivity}" drawable="symfonium"/>

**Comment by basings** [comment]
@Donnnno I am confused. the diff shows a difference between the names of the drawables _0h_h1 and a_0h_h1 . I did not change anything in the appfilter. I only added the app symfonium, yet there are a lot of differences. It's no ASCII error. Do you know what's going on here?

**Comment by ItsJustSomeDude** [comment]
You potentially could have committed on an out-of-date branch.  If your local environment was not up to date with Remote, things like that can break.  `git pull`ing before `git commit`ing should fix it I think.

**Pull request closed without merging**
