### PR TITLE
new icons 

### PR DESCRIPTION
**Pull request by eninkey**
For #466

arcticons_nk

Forgot to check the appfilter first. There are already icons for "chase" and "lucky patcher", right?

### CODE REVIEW

**Comment by Aman9das** [comment]
If there are you can rename yours as original_alt :)

**Comment by eninkey** [comment]
> Is luypatcher the same as luckypatcher? If so, yours is better :^)

Thank you :D
I don't know the app, but because of the "Headline" in appfilter it seems like

**Comment by Donnnno** [comment]
I think it's the same app :)

**Comment by eninkey** [comment]
For #464

arcticons_nk

For calculator, I just added to the appfilter without new icon. Looks similar, I think we dont need a other icon.
calculator

**Comment by eninkey** [comment]
For #470
arcticons_nk

**Comment by Donnnno** [comment]
Woah, looks good!

**Comment by eninkey** [comment]
+ 1 icon

arcticons_nk
n

**Comment by eninkey** [comment]
For #479
arcticons_nk

**Comment by joelchrono12** [comment]
> For #464
> 
> arcticons_nk
> 
> For calculator, I just added to the appfilter without new icon. Looks similar, I think we dont need a other icon. calculator

There is already a pencil in the icon pack, we could just link to that since its basically the saame as yours.

You have done a lot of stuff! Good job

**Comment by Donnnno** [comment]
I noticed this in previous pr's too, but your icons have outline boxes around them, seems quite unnecessary to me.

image

**Comment by Donnnno** [comment]
I've made some small changes to your icons, mostly resizing:
- I removed the twrp app icon, it's a double, but reused the old one in the appfilter.
- SD maid pro looks like the normal SD Maid one, But I've added the smoll to the normal one aswell. 
- Removed unnecessary lines with the wiwinsafekeeping icon. 

image

**Comment by eninkey** [comment]
> 
> 
> I noticed this in previous pr's too, but your icons have outline boxes around them, seems quite unnecessary to me.
> 
> image

I checked my export settings in Affinity Designer. So I have the icons as "ArtBoard". When I export the ArtBort, the outline box is inserted automatically. I can also select only the lines and export, but then the svg is not 48 x 48 and ends directly at the icon. Is this better?

**Comment by eninkey** [comment]
> I've made some small changes to your icons, mostly resizing:

Is there a rule for the size of the icons that I can follow?

**Comment by eninkey** [comment]
> I removed the twrp app icon, it's a double, but reused the old one in the appfilter.

Is there a good way to find out witch icons already exist? This time I hade a look on the appfilter and still there is a double...

**Comment by joelchrono12** [comment]
I believe the Alchemy Starts icon can still be simplified a bit more, I've already done some icons that are kinda similar, removing the eyes and reducing the harilines where they are doubled might make it more Arcticonsy imo

**Comment by joelchrono12** [comment]
I think the Alchemy Stars icon can be simplified a little more, removing eyes and some other lines so its more Arcticon-ish instead of just the white ouline as is

**Comment by Donnnno** [comment]
> 
> 
> > I've made some small changes to your icons, mostly resizing:
> 
> Is there a rule for the size of the icons that I can follow?

My personal rules are: 
- circles 43x43px
- square shapes 37x37
- rectangle shapes max 39px in one of the horizontal of vertical axis

**Comment by Donnnno** [comment]
> 
> 
> > I removed the twrp app icon, it's a double, but reused the old one in the appfilter.
> 
> Is there a good way to find out witch icons already exist? This time I hade a look on the appfilter and still there is a double...

The in-app search function or the one here: onnno.nl/arcticons.html

**Comment by Donnnno** [comment]
> 
> 
> > I noticed this in previous pr's too, but your icons have outline boxes around them, seems quite unnecessary to me.
> > image
> 
> I checked my export settings in Affinity Designer. So I have the icons as "ArtBoard". When I export the ArtBort, the outline box is inserted automatically. I can also select only the lines and export, but then the svg is not 48 x 48 and ends directly at the icon. Is this better?

Ah okey, then so be it, I can remove it easily when I'm checking it.

**Comment by eninkey** [comment]
> I think the Alchemy Stars icon can be simplified a little more, removing eyes and some other lines so its more Arcticon-ish instead of just the white ouline as is

I tried to simplify it, didnt look better for me.
With only dots as eyes, the character was lost.
But feel free to change it.

**Comment by Donnnno** [comment]
On a more ethical note: should we include lucky patcher? I read it can bypass paid functions, sounds not super ethical to me :/

**Comment by joelchrono12** [comment]
Lucky patcher can indeed do that, but in my opinion, thats up to the user.
I used to use it for some apps, I was young, didnt care and didnt have money anyways, either way I would find the apk myself or I would use LP.

I eventually found out the value of software and the work devs put into it, and I eventually bought some of the stuff I actually used.

Besides, LP does not work (afaik) with most modern apps because of different ways of license checking. At the very best it can help adds coins to random games, which get lost once you go online and play and stuff like that.

It will still be decent at some other things, bypassing paid functionality its a good thing if you used to use the app, paid for it, but you are looking to degoogle and cant really get the app any other way. I dont have google in my phone, I use Migrate to backup all data, so I havent lost any of my paid apps, but other people qho dont do that, could find LP useful

**Comment by eninkey** [comment]
I don't have any personal interest in this icon. Just did it for the request and I don't ready have an opinion to this app.

In general: I link that you don't want to support every app, but maybe it should bit somewhere transperent. Maybe just a short note in the app description (under the part about requests) or in the app where you can send requests. I think it's good statment and people don't wonder and wait for this icons.

And we should leave   
`<!-- LuckyPatcher -->`
in the appfilter-file maybe with a hint, so nobody will create the icon again

**Pull request merged**
