### PR TITLE
xml.sh and Vector asset creator guide

### PR DESCRIPTION
**Pull request by Aman9das**

### CODE REVIEW

**Comment by Donnnno** [comment]
Ohhh interesting!

**Comment by Aman9das** [comment]
Triple-T creation.. the graphics in fastlane rn are duotone. if you want me to change something.. feel free to ask

**Comment by Donnnno** [comment]
Wow thanks again for doing this. Was planning on doing this myself tomorrow, haha. 

I'm gonna change the graphics indeed to match the right version ;)

**Comment by Donnnno** [comment]
Oh and changing the build flavor is a button in android studio, at the build variants tab: https://stackoverflow.com/questions/19234499/how-to-build-product-flavors-from-android-studio

**Comment by Donnnno** [comment]
Just finished creating a bunch of new graphics for the new file structure :^)

**Pull request merged**
