### PR TITLE
added 6 icons

### PR DESCRIPTION
**Pull request by joelchrono12**
I added a couple of other icons because yay, I also updated the icon of an already existing app

```xml
<!-- F-Droid Forum -->
<item component="ComponentInfo{at.h4x.fdroidforumclient/at.h4x.fdroidforumclient.MainActivity}" drawable="f-droidforum"/>
<!-- Quinb -->
<item component="ComponentInfo{xyz.deepdaikon.quinb/xyz.deepdaikon.quinb.MainActivity}" drawable="quinb"/>
<!-- PixelDroid -->
<item component="ComponentInfo{org.pixeldroid.app/org.pixeldroid.app.MainActivity}" drawable="pixeldroid"/>
<!-- Brainf -->
<item component="ComponentInfo{com.fredhappyface.brainf/com.fredhappyface.brainf.ActivityMain}" drawable="brainf"/>
<!-- usageDirect -->
<item component="ComponentInfo{godau.fynn.usagedirect/godau.fynn.usagedirect.activity.SourceAppUsageStatisticsActivity}" drawable="usagedirect"/>
<!-- Irregular Expressions -->
<item component="ComponentInfo{mf.asciitext.lite/mf.irregex.SplashScreen}" drawable="irregularexpressions"/>



```
even

### CODE REVIEW

**Comment by joelchrono12** [comment]
Lol, I just tested the latest icon and it looks super cramped xD, I think I will make it simpler looking

**Comment by Donnnno** [comment]
Ohhh nice icons again! The F-Droid Forums one looks great :) 

PixelDroid already has an icon (the same one), it probably isn't applied

**Comment by joelchrono12** [comment]
> Ohhh nice icons again! The F-Droid Forums one looks great :)
Thanks man! its just a simple modification hehe, I did one that followed a design closer to the original, but in the end I just took the already existing f-droid icon and changed it a bit

> PixelDroid already has an icon (the same one), it probably isn't applied
Oh, well, but mine has the camera shutter pentagonal thing, the current one only has an stylized P xD

**Comment by Donnnno** [comment]
> Oh, well, but mine has the camera shutter pentagonal thing, the current one only has an stylized P xD

Oh haha, I was convinced I did the same when I created that icon, but it's only the P indeed. The one with the stutter is more fun to use, I'll just leave the other one in as an alt icon :^)

**Comment by Donnnno** [comment]
Just noticed that the pixeldroid camera shutter wasn't made of lines, so I remade it with lines:

image

**Comment by joelchrono12** [comment]
> Just noticed that the pixeldroid camera shutter wasn't made of lines, so I remade it with lines:

Oh yeah, that's my bad. I still struggle to understand the best way to made things in Inkscape sometimes, but well, at least you fixed it, thanks!

**Comment by Donnnno** [comment]
That's totally understandable! Shapes like these can be hard to get right. 

What I did is combined two circles (one is twice as small), removed all unnecessary lines and rotated it from the middle (360/5) to get the right rotation.

image

**Comment by Donnnno** [comment]
Anyways, I'm not an Inkscape user, so can't help you with that unfortunately

**Comment by joelchrono12** [comment]
> What I did is combined two circles (one is twice as small), removed all unnecessary lines and rotated it from the middle (360/5) to get the right rotation.
Wow that is actually awesome, thanks for this trick, it might be useful the next time I push some icons

**Comment by Donnnno** [comment]
Even better would be to use the fibonacci spiral!
(but that's too complicated for me)

image

**Pull request merged**
