### PR TITLE
fix #1794: errors in dropbox print and signal icons

### LINKED ISSUE #1794: icons print, dropbox and signal are faulty
print.svg has this weird edge
image

signal.svg has sharp edges except for one
image

dropbox.svg has `stroke-linecap:round;stroke-linejoin:round` missing resulting in sharp edges

### PR DESCRIPTION
**Pull request by quantenzitrone**
closes #1794

### CODE REVIEW

**Comment by quantenzitrone** [comment]
Does this work like this? The next release will replace these in icons/{white,black} right?

**Comment by Donnnno** [comment]
Gonna take a look at a different approach for the signal icons, the rounded strokes come too close to each other right now.

**Comment by quantenzitrone** [comment]
i reworked the signal icon, i think i didn't quite get the rounding at the bottom right, but inkscapes dashed paths makes the dashing pretty easy...

**Comment by Donnnno** [comment]
I swear dashes are gonna drive me insane one day. 

Wasn't quite happy with the dashes, so tweaked those to stay true to the original shape.

**Pull request merged**
