### PR TITLE
added 12 icons and app filter

### PR DESCRIPTION
**Pull request by joelchrono12**
All of the icons and missing resources for #382, plus a couple more

icons

### CODE REVIEW

**Comment by joelchrono12** [comment]
That Mobile Legends icon was pretty cool to make, ngl

**Comment by Aman9das** [comment]
Hey edit the appfilter in /other not the one in main/asset/ or main/res/xml

**Comment by joelchrono12** [comment]
> Hey edit the appfilter in /other not the one in main/asset/ or main/res/xml

Wait wut, I have never edited in /other, I directly added to the file. Why the change? :c

**Comment by joelchrono12** [comment]
Anyways, I did it

**Comment by Aman9das** [comment]
Hey just cp -f from aseet to other n it's alright? The change was done as there were 2 spots assets and res/xml

Some people had edited that plus donno had to manually copy paste, now its automated..

**Comment by Donnnno** [comment]
> Some people had edited that plus donno had to manually copy paste, now its automated.

That was a small struggle, but yeah, since the last update it's in /other. 

We should mention that somewhere.

**Pull request merged**
