### PR TITLE
5 new icons

### PR DESCRIPTION
**Pull request by saintpou**
Added 5 icons, 4 of which that are requested icons.
I'm pretty new to GitHub and also vector design, so point out anything I've messed up or things I should've done better.

### CODE REVIEW

**Comment by Donnnno** [comment]
Hey! I can't merge right now, because of the appfilter file? Did you edit it with notepad or something? If you should add it with a code editor like VS Code

**Comment by saintpou** [comment]
The new file uses LF line ending now but the problem remains, what seems to be the issue?

**Comment by Donnnno** [comment]
I think because of all the changes in the past week! Maybe it's the easiest if you rebase your fork and add it again?

**Comment by saintpou** [comment]
Roger that

**Pull request closed without merging**
