### PR TITLE
Add Icon for FRITZ!App WLAN

### PR DESCRIPTION
**Pull request by philosopher0**

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, thanks for your contribution!

I also need the appfilter code to apply it, you can gather it by sending an in-app icon request to yourself or with the turtl app:
https://gitlab.com/xphnx/icon-request-tool

**Comment by joelchrono12** [comment]
> Hi, thanks for your contribution!
> 
> I also need the appfilter code to apply it, you can gather it by sending an in-app icon request to yourself or with the turtl app: https://gitlab.com/xphnx/icon-request-tool

It looks like its a duplicated icon, also, it does not follow the guidelines oof

**Comment by Donnnno** [comment]
Good point, didn't check the icon yet, but please use the font files and try to keep the icon as minimal as possible: 
https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md

**Comment by ddavidd** [comment]
I added the appfilter code for "FRITZ!App WLAN" and used the current 'wlanscanner' icon. For the time being. Or permanently. Whatever you guys decide. 👍

**Comment by Quantenzitrone** [comment]
I remade the icon. I could have kept some components, but I am too perfectionist to leave an asymmetric Wi-Fi symbol uncorrected. It should be in my icon request.

**Comment by Donnnno** [comment]
Thanks!

**Comment by Donnnno** [comment]
resolved in #959

**Pull request closed without merging**
