### PR TITLE
Added 14 new icons 

### PR DESCRIPTION
**Pull request by joelchrono12**
I added the following apps, the svgs are minified, is there a problem with that?
Here is the output from Turtl
```
<!-- Password Store -->
<item component="ComponentInfo{dev.msfjarvis.aps/com.zeapo.pwdstore.LaunchActivity}" drawable="passwordstore"/>
<!-- Yuito -->
<item component="ComponentInfo{net.accelf.yuito/com.keylesspalace.tusky.SplashActivity}" drawable="yuito"/>
<!-- Aurora Services -->
<item component="ComponentInfo{com.aurora.services/com.aurora.services.view.ui.activities.AuroraActivity}" drawable="auroraservices"/>
<!-- Exif Thumbnail Adder -->
<item component="ComponentInfo{com.exifthumbnailadder.app/com.exifthumbnailadder.app.MainActivity}" drawable="exifthumbnailadder"/>
<!-- Agenda -->
<item component="ComponentInfo{com.franco.agenda/com.franco.agenda.activities.Options}" drawable="agenda"/>
<!-- Relay -->
<item component="ComponentInfo{free.reddit.news/reddit.news.RedditNavigation}" drawable="relay"/>
<!-- Stealth -->
<item component="ComponentInfo{com.cosmos.unreddit/com.cosmos.unreddit.MainActivity}" drawable="stealth"/>
<!-- Camera -->
<item component="ComponentInfo{org.stingle.photos/org.stingle.photos.CameraXActivity}" drawable="camera"/>
<!-- DeepL -->
<item component="ComponentInfo{com.example.deeplviewer/com.example.deeplviewer.MainActivity}" drawable="deepl"/>
<!-- Planisphere -->
<item component="ComponentInfo{org.tengel.planisphere/org.tengel.planisphere.MainActivity}" drawable="planisphere"/>
<!-- Resplash -->
<item component="ComponentInfo{com.b_lam.resplash/com.b_lam.resplash.ui.main.MainActivity}" drawable="resplash"/>
<!-- Frameo -->
<item component="ComponentInfo{net.frameo.app/net.frameo.app.ui.activities.AEnterNameAtStartup}" drawable="frameo"/>
<!-- Ultrasonic -->
<item component="ComponentInfo{org.moire.ultrasonic/org.moire.ultrasonic.activity.NavigationActivity}" drawable="ultrasonic"/>
<!-- Stingle Photos -->
<item component="ComponentInfo{org.stingle.photos/org.stingle.photos.GalleryActivity}" drawable="stinglephotos"/>
<!-- Converter NOW -->
<item component="ComponentInfo{com.ferrarid.converterpro/com.ferrarid.converterpro.MainActivity}" drawable="converternow"/>
```

App links:
- [Password Store](https://f-droid.org/packages/dev.msfjarvis.aps)
- [Yuito](https://apt.izzysoft.de/fdroid/repo/net.accelf.yuito)
- [Aurora Services](https://gitlab.com/AuroraOSS/AuroraServices)
- [Exif Thumbnail Adder](https://f-droid.org/en/packages/com.exifthumbnailadder.app/)
- [Calendar Widget](https://play.google.com/store/apps/details?id=com.franco.agenda)
- [Relay for Reddit](https://play.google.com/store/apps/details?id=free.reddit.news&hl=en_US&gl=US)
- [Stealth for reddit](https://f-droid.org/packages/com.cosmos.unreddit/)
- Stingle Camera
- DeepL 
- Planisphere
- Resplash
- Frameo
- Ultrasonic
- Converter NOW

This is my first time making something from scratch (as in, having the original icon as a background layer lol), I had already worked with svg files, but never done anything with Inkscape, you might see me adding some more stuff in the future (if you like these first attempts)

### CODE REVIEW

**Comment by joelchrono12** [comment]
I have been doing icons all day xD, this is quite fun

**Comment by Donnnno** [comment]
Hi! I'll take a look at it tomorrow :) Good to see that you're having fun with it!

**Comment by Donnnno** [comment]
Thanks for your submissions, I'm gonna add them and maybe do some adjustments here and there. I'll let you know if something changes ;)

**Comment by Donnnno** [comment]
I found some small things:
- duplicates: Agenda & Calendar wigdet have the same icon and there are two resplash ones. 
- Deepl & Aurora Services are already in the icon pack, so I'm not gonna include those (I'll update the code for the apps if necessary)

**Comment by joelchrono12** [comment]
> I found some small things:
>     * duplicates: Agenda & Calendar wigdet have the same icon and there are two resplash ones.
>     * Deepl & Aurora Services are already in the icon pack, so I'm not gonna include those (I'll update the code for the apps if necessary)

Thanks, yeah I was messing around with some of the files, didnt remove some duplicates, my bad.
Yeah someone asked me for deepl and I also wanted aurora services since the icon wasnt applied. Good to know they are there, I guess its just the app activity or something is wrong

**Comment by Donnnno** [comment]
Ah, cool.
Some devs are changing the activity names a lot when they update, so that's why that happens.

**Pull request merged**
