### PR TITLE
Added 15 icons

### PR DESCRIPTION
**Pull request by joelchrono12**
I also have added a cleaner icon for the Styx browser which already exists

final

### CODE REVIEW

**Comment by joelchrono12** [comment]
Also, I think the feeder xml got messed up. Here is the one I have
```xml
<!-- Feeder -->
<item component="ComponentInfo{com.nononsenseapps.feeder/com.nononsenseapps.feeder.ui.MainActivity}" drawable="feeder"/>
```

**Comment by Donnnno** [comment]
These look great!

**Comment by Donnnno** [comment]
New drinking game: Every time an Aurora app switches its activity name, you gotta take a shot.

**Comment by Donnnno** [comment]
That sun icon is really well made, I love it!

**Comment by joelchrono12** [comment]
> That sun icon is really well made, I love it!

Man, it was a real pain to do it. I duplicated an 8 pointed star a punch of times, a lot of circles, trying to figure out the difference between the different path functions like "Intersection" "Exclusion" and stuff. In the end I got it, but I already forgot how I did it! xD

**Comment by Donnnno** [comment]
Haha nice!

**Pull request merged**
