### PR TITLE
added icons

### PR DESCRIPTION
**Pull request by basings**
- clear outside
- hotukdeals
- jefit
- qdsldashboard

updated
- mull

### CODE REVIEW

**Comment by basings** [comment]
I wasn't sure if I should delete the mull icon in /icons/black and /icons/white ?

**Comment by basings** [comment]
solves #1287 #1288 #1289

**Comment by basings** [comment]
added 

- streetcomplete_expert_edition

original icon is in a different color than the icon for streetcomplete so no changes for arcticons.

**Comment by Donnnno** [comment]
can you use the already existing streetcomplete or streetcomplete_alt icon instead?

**Comment by basings** [comment]
sure! I wanted to do that first but then I thought if they change the icon in the future, it's only an icon change and not an appfilter change. Hence, I copied the icon. I'll change it later

**Comment by basings** [comment]
done

**Comment by Donnnno** [comment]
Thanks, I get the point, we can always update it in the future if needed :)

**Comment by Donnnno** [comment]
> I wasn't sure if I should delete the mull icon in /icons/black and /icons/white ?

No, it gets automatically replaced!

**Pull request merged**
