### PR TITLE
Added Icons

### PR DESCRIPTION
**Pull request by EdwinRodger**
There was already an icon for dimmer but its item component is different

### CODE REVIEW

**Comment by Donnnno** [comment]
Is the other dimmer icon for another app?

**Comment by EdwinRodger** [comment]
Yes! [Here is the link to it](https://f-droid.org/en/packages/giraffine.dimmer/)<br>
It got discontinued long ago

**Comment by Donnnno** [comment]
ah okay. Can you rename your icon to dimmer_2 ? Without capitalized letters.

**Comment by EdwinRodger** [comment]
Is this ok?

**Comment by Donnnno** [comment]
Yes although it was only needed for the file and the drawable part ;)

**Comment by EdwinRodger** [comment]
There was already a different icon for the app named [Otter](https://github.com/apognu/otter) and the icon I uploaded also named [Otter](https://play.google.com/store/apps/details?id=com.aisense.otter&gl=US) so I changed my icon name from Otter to Otter Notes

**Comment by EdwinRodger** [comment]
I have made [2 icons](other/EdwinRodger/rapido.svg) for [Rapido](https://play.google.com/store/apps/details?id=com.rapido.passenger&gl=US) app
Tell me which one should I keep
(I **did not** made changes for Rapido app yet, only added svg files)

**Comment by Donnnno** [comment]
Hi, I've taken a look at your pr and I noticed some things going on:

- A lot of icons have weird transparency issues, icons should always be white

image

- What am I supposed to see here? Did you use the arcticons font from the arcticons-font repo? You should use the arcticons_font.svg file from the tamplates folder

image

- Sizing is really big right now, take a look at the template and contribution guides for more info:

image

There's a black dot here? 

image

**Comment by EdwinRodger** [comment]
I updated the faulty icons (Mutify, Ola and Spren)
> * What am I supposed to see here? Did you use the arcticons font from the arcticons-font repo? You should use the arcticons_font.svg file from the tamplates folder

Yes I used the arcticons font from the arcticons-font repo and sorry I don't know how to use svg as fonts if there is some guide I am happy to follow

If there are more problems with icons, please ask, I will happily correct them

Also replay to this comment also
https://github.com/Donnnno/Arcticons/pull/1156#issuecomment-1100883570

**Comment by Donnnno** [comment]
> Yes I used the arcticons font from the arcticons-font repo and sorry I don't know how to use svg as fonts if there is some guide I am happy to follow

You have to place the letters manually in your icon instead of just typing. You can drag it from the font svg.

**Comment by EdwinRodger** [comment]
Someone remove [timejot request](https://github.com/Donnnno/Arcticons/blob/b4083b41fc8db095104aaa6a7434173c9d62a98a/other/requests.txt#L1342) from requests.txt
I did all the icons for time being so you can merge the issue and if there are some faulty icons, let me know

**Comment by Donnnno** [comment]
To be honest, it was still a huge mess, but we all have to start somewere:

These are the files you gave me:
image

Here are my corrections:

image

**Pull request merged**
