### PR TITLE
change from nunito to quicksand temporarily and #365

### PR DESCRIPTION
**Pull request by Aman9das**
Does this work?

### CODE REVIEW

**Comment by Aman9das** [comment]
Added 12 icons:
image

**Comment by Aman9das** [comment]
Sorry flipkart was already there.. Dont add it.

**Comment by Donnnno** [comment]
flipcart_alt? I like yours too

**Comment by Aman9das** [comment]
Thanks, i just took the stock shopping element n added a rotated 'f', but sure doesnt hurt, i'll remove the appfilter xml though

**Pull request merged**
