### PR TITLE
Added 3 icons

### PR DESCRIPTION
**Pull request by PoorPocketsMcNewHold**
Verifit : https://github.com/MakisChristou/verifit
https://apt.izzysoft.de/fdroid/index/apk/com.whatever.verifit

sg (Steamgifts) : https://github.com/SteamGifts/SteamGifts
https://f-droid.org/en/packages/net.mabako.steamgifts/

Lavseeker : https://github.com/woheller69/lavatories
https://f-droid.org/en/packages/org.woheller69.lavatories/

First time doing Vector icons entirely by mouse myself. The Inkscape contributing guide extremely helped me. I've used a bit of the vector simplification on some (https://inkscape.org/doc/tutorials/advanced/tutorial-advanced.html) but lightly.

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
Can you also put the code inside the appfilter.xml in /other?

You can gather it with icon request: https://github.com/Kaiserdragon2/IconRequest/releases

**Comment by PoorPocketsMcNewHold** [comment]
[**@Kaiserdragon2**](https://github.com/Kaiserdragon2) commented on [Oct 18, 2022, 4:52 PM UTC](https://github.com/Donnnno/Arcticons/pull/1363#issuecomment-1282701014 "2022-10-18T16:52:03Z - Replied by Github Reply Comments"):
> Can you also put the code inside the appfilter.xml in /other?
> 
> You can gather it with icon request: [https://github.com/Kaiserdragon2/IconRequest/releases](https://github.com/Kaiserdragon2/IconRequest/releases)
Done! I wondered where this file was.

**Comment by Donnnno** [comment]
The icons look good, just did some resizing and shape cleanup (some shapes were kinda messy)

**Comment by PoorPocketsMcNewHold** [comment]
> The icons look good, just did some resizing and shape cleanup (some shapes were kinda messy)

Yeah, I noticed that on release. It was my first vectorial work overall, so it was to be expected. Thanks for reworking them and merging it ! I'll consider working on more for the icon pack.

**Comment by Donnnno** [comment]
That's great to hear!

**Pull request merged**
