### PR TITLE
Added 6 icons

### PR DESCRIPTION
**Pull request by ObsidianChickenz**
Added icons for:
CE Lighting - `com.bolutek.iglootest/com.bolutek.iglootest.ui.activitys.AppStartActivity`
Fitbit - `com.fitbit.FitbitMobile/com.fitbit.FirstActivity`
Guilded - `com.gg.guilded/com.guilded.guildedapp.MainActivity`
LanXchange - `de.tobifleig.lxc/de.tobifleig.lxc.plaf.android.activity.MainActivity`
Life360 - `com.life360.android.safetymapd/com.life360.koko.root.RootActivity`
Remind - `com.remind101/com.remind101.splash.SplashActivity`

I hope these icons are up to standard.

### CODE REVIEW

**Comment by Donnnno** [comment]
I'll look at the icons tomorrow! 

Can you get the unmodified turtl info?

**Comment by ObsidianChickenz** [comment]
Where does Turtl save info? I'm looking for it right now and can't find it.

**Comment by Donnnno** [comment]
The copy to clipboard function should fo the work

**Comment by ObsidianChickenz** [comment]
Directly from Turtl:


<item component="ComponentInfo{com.bolutek.iglootest/com.bolutek.iglootest.ui.activitys.AppStartActivity}" drawable="celighting"/>

<item component="ComponentInfo{com.fitbit.FitbitMobile/com.fitbit.FirstActivity}" drawable="fitbit"/>

<item component="ComponentInfo{com.gg.guilded/com.guilded.guildedapp.MainActivity}" drawable="guilded"/>

<item component="ComponentInfo{de.tobifleig.lxc/de.tobifleig.lxc.plaf.android.activity.MainActivity}" drawable="lanxchange"/>

<item component="ComponentInfo{com.life360.android.safetymapd/com.life360.koko.root.RootActivity}" drawable="life360"/>

<item component="ComponentInfo{com.remind101/com.remind101.splash.SplashActivity}" drawable="remind"/>

**Comment by Donnnno** [comment]
Yes! Thanks :^)

**Comment by Donnnno** [comment]
fixed sizing & line thickness, other than that the icons are looking very good :)

**Pull request merged**
