### PR TITLE
Make the request.txt more Appfilter styled.

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
The convert_request.py is only needed once to convert the current request.txt after that the new email_parser.py can be used to update the request.txt.
The convert_request.py is used exactly like the email_parser.py
grafik

### CODE REVIEW

**Comment by Donnnno** [comment]
Not all heroes capes..

**Comment by Donnnno** [comment]
So the convert one is only needed once?

**Comment by Kaiserdragon2** [comment]
oh you have also declare the appfilter and email path because its only an modifiyed version of the email parser

**Comment by Donnnno** [comment]
Yes! perfect, thank you for making this!

**Pull request merged**
