### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pawann-2000**
bigbasket logo added

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, please check out the contribution guide, the icon doesn't match our style right now.
https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md

Also what is going on here?
image

**Comment by pawann-2000** [comment]
Oops, let me fix it :wrench:

**Comment by pawann-2000** [comment]
image
it does look like this when I'm editing, how can I export it as it looks to an svg :thinking:

**Comment by Donnnno** [comment]
Very strange, but besides that, you have to use the font that's included in the templates folder and make sure the line thickness is 1px

**Comment by Donnnno** [comment]
hows it going with this one?

**Comment by dgcampbe** [comment]
Did the merged pull request resolve this?

**Comment by Donnnno** [comment]
Yess

**Pull request closed without merging**
