### PR TITLE
Added icons for #208 and #207

### PR DESCRIPTION
**Pull request by joelchrono12**
I added the icons from #207 and #208, I also redesigned the icons for Deedum

```
<!-- deedum -->
<item component="ComponentInfo{ca.snoe.deedum/ca.snoe.deedum.MainActivity}" drawable="deedum"/>
<!-- neutriNote CE -->
<item component="ComponentInfo{com.appmindlab.nano/com.appmindlab.nano.IntroActivity}" drawable="neutrinotece"/>
<!-- OpenLP -->
<item component="ComponentInfo{org.openlp.android2/org.openlp.android2.OpenLP}" drawable="openlp"/>
<!-- lemmur -->
<item component="ComponentInfo{com.krawieck.lemmur/com.krawieck.lemmur.MainActivity}" drawable="lemmur"/>
```

### CODE REVIEW

**Comment by Donnnno** [comment]
Thanks! Great work :)

**Comment by joelchrono12** [comment]
Since this has not been merged yet I took the time to make a couple more icons

**Comment by Donnnno** [comment]
Thanks, I'll add them hopefully later this week when I have some time :)

**Comment by joelchrono12** [comment]
Another icon for lemmur, done

**Pull request merged**
