### PR TITLE
Add vector/raster icons for 5 apps plus placeholders

### PR DESCRIPTION
**Pull request by livmackintosh**
Duorem
Monzo
Nationwide
OpenHabBeta
Quasseldroid

To-do:
- [x]  Rename openhabbeta.(svg|png) -> openhab.(svg|png)
- [x]  Add non-beta openhab too
- [x]  Tidy up placeholders (inc. Movim which borrows forecastie icon for now)
- [x]  Once-over

### CODE REVIEW

**Comment by Donnnno** [comment]
Thanks! The icons look very good :) 

Just a couple things:
- can you place the svg's in the `other` folder instead of the `icons` folder
- you also don't need to export the png's (I rather do that myself) 
- you also don't need to add it to the `drawable.xml` and `iconpack.xml` files (I have a script that does that automatically)

**Comment by livmackintosh** [comment]
Done.

**Comment by Donnnno** [comment]
Thanks! :^)

**Comment by Donnnno** [comment]
One thing I noticed that the icons were kinda small, I changed that to fit them more with the other icons. 
Other than that, good work!

**Pull request merged**
