### PR TITLE
24 New Icons

### PR DESCRIPTION
**Pull request by ChadFacts**
Hi! The app updated while I was making these icons, so some may be copies of new icons. My bad if some are. Also, I've never worked with SVGs before so sorry for any mistakes. Same if I fucked up on the style for a few of them. I did my best, I'm not much of an artist. Literally my first time ever using Inkscape, I was going to use GIMP but realized that wouldn't work out with SVGs.

Here's the list from turtl:

<item component="ComponentInfo{com.aidungeon/com.aidungeon.MainActivity}" drawable="aidungeon"/>

<item component="ComponentInfo{com.amazon.dee.app/com.amazon.dee.app.Launcher}" drawable="amazonalexa"/>

<item component="ComponentInfo{network.xyo.coin/network.xyo.coin.LoginActivity}" drawable="coin"/>

<item component="ComponentInfo{com.razer.cortex/com.razer.cortex.ui.main.MainActivity}" drawable="cortexgames"/>

<item component="ComponentInfo{com.pixplicity.cryptogram/com.pixplicity.cryptogram.activities.CryptogramActivity}" drawable="cryptogram"/>

<item component="ComponentInfo{net.daylio/net.daylio.activities.OverviewActivity}" drawable="daylio"/>

<item component="ComponentInfo{com.dolby.daxappui/com.dolby.daxappui.MainActivity}" drawable="dolbyatmos"/>

<item component="ComponentInfo{com.coffeebeanventures.easyvoicerecorder/com.digipom.easyvoicerecorder.ui.activity.EasyVoiceRecorderActivity}" drawable="easyvoicerecorder"/>

<item component="ComponentInfo{com.ecobee.athenamobile/com.ecobee.athenamobile.launcher.LauncherActivity}" drawable="ecobee"/>

<item component="ComponentInfo{com.sillens.shapeupclub/com.sillens.shapeupclub.MainActivity}" drawable="lifesum"/>

<item component="ComponentInfo{manevolves.mdf/manevolves.mdf.MainActivity}" drawable="mdf"/>

<item component="ComponentInfo{com.free.music.app/com.free.music.app.activities.TabsActivity}" drawable="mu"/>

<item component="ComponentInfo{com.musixmatch.android.lyrify/com.musixmatch.android.presentation.activities.SplashActivity}" drawable="musixmatch"/>

<item component="ComponentInfo{com.netgear.netgearup/com.netgear.netgearup.core.view.WizardActivity}" drawable="nighthawk"/>

<item component="ComponentInfo{com.ennesoft.paint/com.ennesoft.paint.SplashScreen}" drawable="paint"/>

<item component="ComponentInfo{cn.danatech.xingseus/com.xingse.app.kt.view.home.SplashActivity}" drawable="picturethis"/>

<item component="ComponentInfo{org.plantnet/org.plantnet.MainActivity}" drawable="plantnet"/>

<item component="ComponentInfo{com.shamanland.privatescreenshots/com.shamanland.privatescreenshots.main.Launcher}" drawable="privatescreenshots"/>

<item component="ComponentInfo{com.sec.android.app.shealth/com.samsung.android.app.shealth.home.HomeMainActivity}" drawable="samsunghealth"/>

<item component="ComponentInfo{in.sweatco.app/com.app.sweatcoin.ui.activities.RootActivity}" drawable="sweatcoin"/>

<item component="ComponentInfo{com.sflpro.aop/com.sflpro.aop.authorisation.view.splash.activity.SplashActivity}" drawable="truepublic"/>

<item component="ComponentInfo{com.qidian.Int.reader/com.qidian.Int.reader.SplashActivity}" drawable="webnovel"/>

<item component="ComponentInfo{com.naver.linewebtoon/com.naver.linewebtoon.splash.SplashActivity}" drawable="webtoon"/>

<item component="ComponentInfo{com.yeelight.cherry/com.yeelight.cherry.ui.activity.LauncherActivity}" drawable="yeelight"/>

### CODE REVIEW

**Comment by ChadFacts** [comment]
<-- AIDungeon -->
<item component="ComponentInfo{com.aidungeon/com.aidungeon.MainActivity}" drawable="aidungeon"/>
<-- Amazon Alexa -->
<item component="ComponentInfo{com.amazon.dee.app/com.amazon.dee.app.Launcher}" drawable="amazonalexa"/>
<-- COIN -->
<item component="ComponentInfo{network.xyo.coin/network.xyo.coin.LoginActivity}" drawable="coin"/>
<-- Cortex Games -->
<item component="ComponentInfo{com.razer.cortex/com.razer.cortex.ui.main.MainActivity}" drawable="cortexgames"/>
<-- Cryptogram -->
<item component="ComponentInfo{com.pixplicity.cryptogram/com.pixplicity.cryptogram.activities.CryptogramActivity}" drawable="cryptogram"/>
<-- Daylio -->
<item component="ComponentInfo{net.daylio/net.daylio.activities.OverviewActivity}" drawable="daylio"/>
<-- Dolby Atmos -->
<item component="ComponentInfo{com.dolby.daxappui/com.dolby.daxappui.MainActivity}" drawable="dolbyatmos"/>
<-- Easy Voice Recorder -->
<item component="ComponentInfo{com.coffeebeanventures.easyvoicerecorder/com.digipom.easyvoicerecorder.ui.activity.EasyVoiceRecorderActivity}" drawable="easyvoicerecorder"/>
<-- ecobee -->
<item component="ComponentInfo{com.ecobee.athenamobile/com.ecobee.athenamobile.launcher.LauncherActivity}" drawable="ecobee"/>
<-- Lifesum -->
<item component="ComponentInfo{com.sillens.shapeupclub/com.sillens.shapeupclub.MainActivity}" drawable="lifesum"/>
<-- mdf -->
<item component="ComponentInfo{manevolves.mdf/manevolves.mdf.MainActivity}" drawable="mdf"/>
<-- MU -->
<item component="ComponentInfo{com.free.music.app/com.free.music.app.activities.TabsActivity}" drawable="mu"/>
<-- Musixmatch -->
<item component="ComponentInfo{com.musixmatch.android.lyrify/com.musixmatch.android.presentation.activities.SplashActivity}" drawable="musixmatch"/>
<-- Nighthawk -->
<item component="ComponentInfo{com.netgear.netgearup/com.netgear.netgearup.core.view.WizardActivity}" drawable="nighthawk"/>
<-- Paint -->
<item component="ComponentInfo{com.ennesoft.paint/com.ennesoft.paint.SplashScreen}" drawable="paint"/>
<-- PictureThis -->
<item component="ComponentInfo{cn.danatech.xingseus/com.xingse.app.kt.view.home.SplashActivity}" drawable="picturethis"/>
<-- PlantNet -->
<item component="ComponentInfo{org.plantnet/org.plantnet.MainActivity}" drawable="plantnet"/>
<-- Private Screenshots -->
<item component="ComponentInfo{com.shamanland.privatescreenshots/com.shamanland.privatescreenshots.main.Launcher}" drawable="privatescreenshots"/>
<-- Samsung Health -->
<item component="ComponentInfo{com.sec.android.app.shealth/com.samsung.android.app.shealth.home.HomeMainActivity}" drawable="samsunghealth"/>
<-- Sweatcoin -->
<item component="ComponentInfo{in.sweatco.app/com.app.sweatcoin.ui.activities.RootActivity}" drawable="sweatcoin"/>
<-- TruePublic -->
<item component="ComponentInfo{com.sflpro.aop/com.sflpro.aop.authorisation.view.splash.activity.SplashActivity}" drawable="truepublic"/>
<-- Webnovel -->
<item component="ComponentInfo{com.qidian.Int.reader/com.qidian.Int.reader.SplashActivity}" drawable="webnovel"/>
<-- WEBTOON -->
<item component="ComponentInfo{com.naver.linewebtoon/com.naver.linewebtoon.splash.SplashActivity}" drawable="webtoon"/>
<-- Yeelight -->
<item component="ComponentInfo{com.yeelight.cherry/com.yeelight.cherry.ui.activity.LauncherActivity}" drawable="yeelight"/>

**Comment by ChadFacts** [comment]
AIDungeon
<item component="ComponentInfo{com.aidungeon/com.aidungeon.MainActivity}" drawable="aidungeon"/>
Amazon Alexa
<item component="ComponentInfo{com.amazon.dee.app/com.amazon.dee.app.Launcher}" drawable="amazonalexa"/>
COIN
<item component="ComponentInfo{network.xyo.coin/network.xyo.coin.LoginActivity}" drawable="coin"/>
Cortex Games
<item component="ComponentInfo{com.razer.cortex/com.razer.cortex.ui.main.MainActivity}" drawable="cortexgames"/>
Cryptogram
<item component="ComponentInfo{com.pixplicity.cryptogram/com.pixplicity.cryptogram.activities.CryptogramActivity}" drawable="cryptogram"/>
Daylio
<item component="ComponentInfo{net.daylio/net.daylio.activities.OverviewActivity}" drawable="daylio"/>
Dolby Atmos
<item component="ComponentInfo{com.dolby.daxappui/com.dolby.daxappui.MainActivity}" drawable="dolbyatmos"/>
Easy Voice Recorder
<item component="ComponentInfo{com.coffeebeanventures.easyvoicerecorder/com.digipom.easyvoicerecorder.ui.activity.EasyVoiceRecorderActivity}" drawable="easyvoicerecorder"/>
ecobee
<item component="ComponentInfo{com.ecobee.athenamobile/com.ecobee.athenamobile.launcher.LauncherActivity}" drawable="ecobee"/>
Lifesum
<item component="ComponentInfo{com.sillens.shapeupclub/com.sillens.shapeupclub.MainActivity}" drawable="lifesum"/>
mdf
<item component="ComponentInfo{manevolves.mdf/manevolves.mdf.MainActivity}" drawable="mdf"/>
MU
<item component="ComponentInfo{com.free.music.app/com.free.music.app.activities.TabsActivity}" drawable="mu"/>
Musixmatch
<item component="ComponentInfo{com.musixmatch.android.lyrify/com.musixmatch.android.presentation.activities.SplashActivity}" drawable="musixmatch"/>
Nighthawk
<item component="ComponentInfo{com.netgear.netgearup/com.netgear.netgearup.core.view.WizardActivity}" drawable="nighthawk"/>
Paint
<item component="ComponentInfo{com.ennesoft.paint/com.ennesoft.paint.SplashScreen}" drawable="paint"/>
PictureThis
<item component="ComponentInfo{cn.danatech.xingseus/com.xingse.app.kt.view.home.SplashActivity}" drawable="picturethis"/>
PlantNet
<item component="ComponentInfo{org.plantnet/org.plantnet.MainActivity}" drawable="plantnet"/>
Private Screenshots
<item component="ComponentInfo{com.shamanland.privatescreenshots/com.shamanland.privatescreenshots.main.Launcher}" drawable="privatescreenshots"/>
Samsung Health
<item component="ComponentInfo{com.sec.android.app.shealth/com.samsung.android.app.shealth.home.HomeMainActivity}" drawable="samsunghealth"/>
Sweatcoin
<item component="ComponentInfo{in.sweatco.app/com.app.sweatcoin.ui.activities.RootActivity}" drawable="sweatcoin"/>
TruePublic
<item component="ComponentInfo{com.sflpro.aop/com.sflpro.aop.authorisation.view.splash.activity.SplashActivity}" drawable="truepublic"/>
Webnovel
<item component="ComponentInfo{com.qidian.Int.reader/com.qidian.Int.reader.SplashActivity}" drawable="webnovel"/>
WEBTOON
<item component="ComponentInfo{com.naver.linewebtoon/com.naver.linewebtoon.splash.SplashActivity}" drawable="webtoon"/>
Yeelight
<item component="ComponentInfo{com.yeelight.cherry/com.yeelight.cherry.ui.activity.LauncherActivity}" drawable="yeelight"/>

**Comment by ChadFacts** [comment]
AIDungeon
item component="ComponentInfo{com.aidungeon/com.aidungeon.MainActivity}" drawable="aidungeon"/
Amazon Alexa
item component="ComponentInfo{com.amazon.dee.app/com.amazon.dee.app.Launcher}" drawable="amazonalexa"/
COIN
item component="ComponentInfo{network.xyo.coin/network.xyo.coin.LoginActivity}" drawable="coin"/
Cortex Games
item component="ComponentInfo{com.razer.cortex/com.razer.cortex.ui.main.MainActivity}" drawable="cortexgames"/
Cryptogram
item component="ComponentInfo{com.pixplicity.cryptogram/com.pixplicity.cryptogram.activities.CryptogramActivity}" drawable="cryptogram"/
Daylio
item component="ComponentInfo{net.daylio/net.daylio.activities.OverviewActivity}" drawable="daylio"/
Dolby Atmos
item component="ComponentInfo{com.dolby.daxappui/com.dolby.daxappui.MainActivity}" drawable="dolbyatmos"/
Easy Voice Recorder
item component="ComponentInfo{com.coffeebeanventures.easyvoicerecorder/com.digipom.easyvoicerecorder.ui.activity.EasyVoiceRecorderActivity}" drawable="easyvoicerecorder"/
ecobee
item component="ComponentInfo{com.ecobee.athenamobile/com.ecobee.athenamobile.launcher.LauncherActivity}" drawable="ecobee"/
Lifesum
<item component="ComponentInfo{com.sillens.shapeupclub/com.sillens.shapeupclub.MainActivity}" drawable="lifesum"/>
mdf
item component="ComponentInfo{manevolves.mdf/manevolves.mdf.MainActivity}" drawable="mdf"/
MU
item component="ComponentInfo{com.free.music.app/com.free.music.app.activities.TabsActivity}" drawable="mu"/
Musixmatch
item component="ComponentInfo{com.musixmatch.android.lyrify/com.musixmatch.android.presentation.activities.SplashActivity}" drawable="musixmatch"/
Nighthawk
item component="ComponentInfo{com.netgear.netgearup/com.netgear.netgearup.core.view.WizardActivity}" drawable="nighthawk"/
Paint
item component="ComponentInfo{com.ennesoft.paint/com.ennesoft.paint.SplashScreen}" drawable="paint"/
PictureThis
item component="ComponentInfo{cn.danatech.xingseus/com.xingse.app.kt.view.home.SplashActivity}" drawable="picturethis"/
PlantNet
item component="ComponentInfo{org.plantnet/org.plantnet.MainActivity}" drawable="plantnet"/
Private Screenshots
item component="ComponentInfo{com.shamanland.privatescreenshots/com.shamanland.privatescreenshots.main.Launcher}" drawable="privatescreenshots"/
Samsung Health
item component="ComponentInfo{com.sec.android.app.shealth/com.samsung.android.app.shealth.home.HomeMainActivity}" drawable="samsunghealth"/
Sweatcoin
item component="ComponentInfo{in.sweatco.app/com.app.sweatcoin.ui.activities.RootActivity}" drawable="sweatcoin"/
TruePublic
item component="ComponentInfo{com.sflpro.aop/com.sflpro.aop.authorisation.view.splash.activity.SplashActivity}" drawable="truepublic"/
Webnovel
item component="ComponentInfo{com.qidian.Int.reader/com.qidian.Int.reader.SplashActivity}" drawable="webnovel"/
WEBTOON
item component="ComponentInfo{com.naver.linewebtoon/com.naver.linewebtoon.splash.SplashActivity}" drawable="webtoon"/
Yeelight
item component="ComponentInfo{com.yeelight.cherry/com.yeelight.cherry.ui.activity.LauncherActivity}" drawable="yeelight"/

**Comment by ChadFacts** [comment]
Oh and if you see any mistakes I made, advice on them would be useful. I know I'm asking a lot with that but it would be nice.

**Comment by Donnnno** [comment]
Hi, thanks for your first pull request. I'm noticing a couple of things wrong with your icons that have to be fixed first.
You can find most things on the contribution page here: [Contributing.md](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md)

- Line thickness: This should **always** be 1pt/px (depending on what program you use), this is for consistency within each icon. I'm seeing a lot of different sizes, some aren't even lines (you can check out the [frost ](https://github.com/dkanada/frost)icon pack if you want more variety in how it looks)
- Document size: the size of the document is always 48x48 px like in the template files, use those to start with. I'm seeing a lot of different artboard sizes, please don't do that.
- Sizing, I've set up a couple of basic shapes to work from in the `templates` folder you can take a look at those for that. For example, circles are 43x43px and rounded squares 37x37px etc. use those files as a baseline for your icons.
- Don't use too many unnecessary shapes, I'm seeing a lot of icons with shapes within shapes for example circles within circles. This is kinda not needed in most cases and will make your icon harder to recognize,

I hope you're able to fix these things, good luck!

**Comment by ChadFacts** [comment]
I think with the last one you're referring to the COIN app's icon, that's how the icon looks and I didn't know what to replace it with so I made that.

I also never even knew svg's came in sizes really, so I will look into fixing that.

**Pull request closed without merging**
