### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by ktutsch**
https://github.com/Donnnno/Arcticons/pull/1146#issuecomment-1095462846 I hope that I applied all your tips for these new icons.

### CODE REVIEW

**Comment by ktutsch** [comment]
Some icons of this request got added later:

### ONLYOFFICE Documents
*First:* https://github.com/ktutsch/Arcticons/commit/6aad2d7ca8b2d2ebaf25121f68da3648dfc4aaa9
*Then:* https://github.com/Kaiserdragon2/Arcticons/commit/b6d275a57646b96021bbbf1f83d1bda7629f3347

### PDF Viewer
*First:* https://github.com/ktutsch/Arcticons/commit/6e9050bc8269de1ff44c7cbcbba3c638ee26acf4
*Then:* https://github.com/Donnnno/Arcticons/commit/bc88f12f39aa6ccaa51025f833e8e0119ea3132d

What will happen with my icons? Should I revert the commits?

**Comment by Donnnno** [comment]
I wanted to comment about the PDF one! 
We already have a standard PDF icon, but it had a weird name, so I renamed it yesterday. You can leave that one out of the pr.

We'll decide later about the onlyoffice icon, so leave it in the pr.

**Comment by Donnnno** [comment]
So there were pretty weird things going on with the sizing of a lot of the icons, a lot of the time the canvas was only 12,7 px 

image

That's fixed now/.

**Comment by Donnnno** [comment]
Overall great work again! Love the icons and your hard work :)

**Comment by ktutsch** [comment]
Should be fixed with my next icons. I set height and width in "Document properties -> Custom", but when only saving the viewbox, they need to be set in "Document properties -> Scaling -> Viewbox...".

**Comment by Donnnno** [comment]
Ah okey, cool!

**Pull request merged**
