### PR TITLE
Added icons

### PR DESCRIPTION
**Pull request by Th3Third3ye**
Added the following app icons:
Athan
CashKaro
Finance
Retouche Photo - Polish
Shopsy
Songsterr

### CODE REVIEW

**Comment by Donnnno** [comment]
Nice!

**Comment by Donnnno** [comment]
Great work on the icons again! But getting some merge errors, so adding it in a different PR again. 

Can you add all your appfilter entries in one place next time? (doesn't matter where, because it gets sorted every release)

**Comment by Th3Third3ye** [comment]
Oh okay, i will make sure to do that next time! sorry for the trouble

**Comment by Donnnno** [comment]
No problem at all!

**Pull request closed without merging**
