### PR TITLE
Add few icons and (hopefully) all the relevant stuff

### PR DESCRIPTION
**Pull request by 0slav**
Not a designer so there's a risk I've done something terribly wrong (for example I'm not sure how to choose the right size other than "it fits within the circle")
Original: 
lbry

### CODE REVIEW

**Comment by TBog** [comment]
I don't see the icon in your PR

**Comment by 0slav** [comment]
Sorry, my bad, forgot add

**Comment by Donnnno** [comment]
Hi, good work. A couple of things: 
- can you place the svg's in the `other` folder instead of the `icons` folder
- you also don't need to export the png's (I rather do that myself) 
- you also don't need to add it to the `drawable.xml` and `iconpack.xml` files (I have a script that does that automatically)

**Comment by 0slav** [comment]
Yeah, I found the scripts :P Noted for the future

**Comment by Donnnno** [comment]
Thanks!

**Comment by Donnnno** [comment]
It looks good! Did a tiny bit of cleanup (less anchor points mostly) and changed the caps & corners to round (I should add that to the contributing file)

**Pull request merged**
