### PR TITLE
Uptated appfilter.xml

### PR DESCRIPTION
**Pull request by shreyanshs31**
Added Ajio and Package name app icon request

### CODE REVIEW

**Comment by Donnnno** [comment]
But without icons 🙃...

**Comment by shreyanshs31** [comment]
I have made icons as per instruction I forked the repo then I made pull request.
The instructions I followed is also attached in mail.
Please let me know If I have missed anything as this will be my first commit.
Thank you

-------- Original Message --------

**Comment by Lavin-tom** [comment]
Hello @shreyanshs31, I think you did not copy those icons(SVG format) into "other" folder in the repo.

**Comment by shreyanshs31** [comment]
Hey there, can you see it now in the other folder the Ajio_app.svg and Package_name.svg. I have made some changes .
Thank you for your responding.
Shreyansh

-------- Original Message --------

**Pull request closed without merging**
