### PR TITLE
added Icons

### PR DESCRIPTION
**Pull request by basings**
- meine_aok
- substreamer
- ~~ard_audiothek~~
- ~~ard_mediathek~~

### CODE REVIEW

**Comment by basings** [comment]
- ard_mediathek

**Comment by basings** [comment]
ard_audiothek

**Comment by Donnnno** [comment]
The ARD icon already exists, and I just linked it to each other in a commit earlier this week :)

**Comment by Donnnno** [comment]
but nice work!

**Comment by basings** [comment]
Wow! That's a weird coincidence :D

Thanks

**Comment by basings** [comment]
added following icons 

- aldi_mobile
- aldi_sd
- aldi_shop_and_go
- aldi_shop_go
- aldigo

**Comment by basings** [comment]
updated:
- schildichat
- element

**Comment by basings** [comment]
added: 

- boostcamp
- every door
- everywhere launcher
- everywhere launcher unlocker
- kitchenowl
- moon phase
- opentracks
- workit

**Comment by basings** [comment]
added: 
- body_measures
- fujiten
- psms
- super_status_bar
- widgets

**Comment by Donnnno** [comment]
I've made some modifications to the ALDI icons, it's more unified now:

image

**Pull request merged**
