### PR TITLE
New activity name for Komoot + some new icons

### PR DESCRIPTION
**Pull request by eninkey**
The Komoot-icon doesn't work on my device. With adding this line, it should fix it, right? (It's from my Turtl export)

### CODE REVIEW

**Comment by Aman9das** [comment]
Yes it should, if not then there is some drawable problem..

**Comment by eninkey** [comment]
Adobe Acrobat does not work for me either. 
But the two lines look the same, except for what "drawable" is
Maybe the name of image file is wrong?

In the appfilter.xml:
```
<!-- Adobe Acrobat -->
<item component="ComponentInfo{com.adobe.reader/com.adobe.reader.AdobeReader}" drawable="acrobat" />

```
from my Turtl:
```
<!-- Adobe Acrobat -->
<item component="ComponentInfo{com.adobe.reader/com.adobe.reader.AdobeReader}" drawable="adobeacrobat"/>
```

**Comment by Aman9das** [comment]
Thanks for pointing that out, yes we need to fix the drawable name
Im done for the day, but I'll make the fix tomorrow for sure, of someone else doesn't do it already :)

Thanks for pointing it out though!

**Comment by eninkey** [comment]
Ok :)

**Comment by eninkey** [comment]
And some new icons :)
SomeNewIcons

**Comment by eninkey** [comment]
> 
> 
> Adobe Acrobat does not work for me either.
> But the two lines look the same, except for what "drawable" is
> Maybe the name of image file is wrong?
> 
> In the appfilter.xml:
> 
> ```
> 
> <item component="ComponentInfo{com.adobe.reader/com.adobe.reader.AdobeReader}" drawable="acrobat" />
> ```
> 
> from my Turtl:
> 
> ```
> 
> <item component="ComponentInfo{com.adobe.reader/com.adobe.reader.AdobeReader}" drawable="adobeacrobat"/>
> ```


> 
> 
> Thanks for pointing that out, yes we need to fix the drawable name
> Im done for the day, but I'll make the fix tomorrow for sure, of someone else doesn't do it already :)
> 
> Thanks for pointing it out though!

I made a new Issue for better overview :)

**Comment by Aman9das** [comment]
Great!

**Comment by Donnnno** [comment]
Great work! 
I've made some tiny adjustments to the icons.

**Comment by Donnnno** [comment]
I've merged your Pull request, but something went wrong on my part, I guess.
Anyways all your work is included now, so no worries about me closing this issue.

**Comment by eninkey** [comment]
> I've made some tiny adjustments to the icons.

If there is something which I can improve, let me know.

**Pull request closed without merging**
