### PR TITLE
Anymex and AnymeUltima

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Added icons for Anymex and AnymeUltima and added them to the appfilter.xml

### CODE REVIEW

**Comment by Donnnno** [comment]
Nice!

But why is has the appfilter so many changes?

**Comment by Kaiserdragon2** [comment]
Oh, I tested the icons and build the app myself and used the sort.sh

**Comment by Donnnno** [comment]
Ah, okay, I'd rather not use the sort function because it removes the dynamic calendar icons from the appfilter list.

**Comment by Donnnno** [comment]
thanks for the fix :)

**Pull request merged**
