### PR TITLE
New icons and small fixes

### PR DESCRIPTION
**Pull request by totoroot**
Hey Donnno,

Thanks for the recent releases and your continued maintaining efforts! I've found some time for a contribution of my own again.

- the activity name for the app "Radio FM4" changed with the most recent update and broke the association with the previously created icon. This is fixed in commit 6c5172209e409c0fcbb428e09a5c2c00eb7d2d3d.

- added icon for "MeineSV"

  [Google Play page](https://play.google.com/store/apps/details?id=at.itsv.mobile.meinesvstatus&hl=en_US&gl=US)

  meinesv-app-logo   meinesv-icon-logo-overlay   meinesv-icon

- added icon for "Beelinguapp"

  [Google Play page](https://play.google.com/store/apps/details?id=com.david.android.languageswitch&hl=en_US&gl=US)
  
  beelinguapp-app-logo  beelinguapp-icon-logo-overlay   beelinguapp-icon
  
- added an icon association for "Android IP Scanner" from IzzyOnDroid/F-Droid with commit ec681adbc435b43a285d76ada895bb955a9e180d

  The app's logo is simply a WiFi symbol so I reckon we can use the standard wifi icon (https://github.com/victorbnl/android-ip-scanner)

I think that should be it for now :)

### CODE REVIEW

**Comment by totoroot** [comment]
On second thought I'm not quite sure if these new icons actually need the frame...
Please feel free to remove it ior let me know if I should change this or anything else.

**Comment by Donnnno** [comment]
Hi! Thanks for your icons!!

I've deleted the boxes because the icons don't need them :)

image

Also, can you leave them with a white color in the /other folder next time? 

Great work!

**Comment by totoroot** [comment]
Thanks! Sorry, apparently I forgot where to place them.
I'll make sure to add the next ones there then :)

**Comment by Donnnno** [comment]
Cool!

**Pull request merged**
