### PR TITLE
Adds luca and lucia app icons

### PR DESCRIPTION
**Pull request by chaptergy**
luca
lucia

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, I can't open these svg's, did you export them correctly?

**Comment by chaptergy** [comment]
I am able to open the svgs without any issues. I have now saved them in a non-optimized way, maybe then you will be able to open them.

**Comment by Donnnno** [comment]
Ah it works now.

A small suggestion would be to use the lowercase letters because the original app also uses lowercases. But I'll leave that up to you to decide :^)

**Comment by chaptergy** [comment]
You're right, that would fit better. I've changed it, thanks!

**Comment by Donnnno** [comment]
Cool!

**Pull request merged**
