### PR TITLE
Added New Icons

### PR DESCRIPTION
**Pull request by asankaSovis**
Added new icons for the following:
- Domino's Sri Lanka
- Helakuru
- Helakuru Lite
- Sri Lankan Airlines
- Viu
- ZapMail

### CODE REVIEW

**Comment by Donnnno** [comment]
Great work! 

We could probably just use the default icon for Domino's SL right? Looks somewhat cleaner :)

**Comment by asankaSovis** [comment]
Thanks!

Do you mean the Domino's icon without the 'SL' in it? I took inspiration from the other Domino's apps, like this one for Canada:
image

**Comment by Donnnno** [comment]
Ah yea, thought so. I was actually thinking about removing those 😅

**Comment by asankaSovis** [comment]
In that case, we'll go with the originals. No problem.

**Comment by Donnnno** [comment]
image

Changed some things, please keep in mind that icons are lines only, so no fill elements are allowed, like the text you've put in the icons :)

**Comment by asankaSovis** [comment]
Ahhhhh, so sorry about that. Ill keep that in mind.

**Comment by Donnnno** [comment]
no worries~!

**Pull request merged**
