### PR TITLE
change spaces to tab

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Just some beauty stuff

this changes the xml files to be the same with newly created ones from my changes in the release script

### CODE REVIEW

**Comment by Donnnno** [comment]
okey this commit only changes existing icons right?

**Comment by Kaiserdragon2** [comment]
yes

**Comment by Donnnno** [comment]
Commits like these always feel a bit scary to merge 😅

**Comment by Kaiserdragon2** [comment]
Understandable its a huge amount of changes

**Pull request merged**
