### PR TITLE
New Icons

### PR DESCRIPTION
**Pull request by onuronsekiz**
I noticed most car and motorcycle brand icons are missing.
So here they are; 22 New Icons and 29 Appfilter Entries

1. Algorithms
2. Arabam
3. My BMW (*)
4. BMW Türkiye (*)
5. Campu.eu
6. My Dacia (**)
7. Dacia Media Control (**)
8. Fiat Yol Arkadaşım
9. Harley Davidson
10. Honda Bikes
11. Honda Connect
12. Mazda
13. myChevrolet
14. My Citroën
15. MyFerrari
16. myHyundai
17. Kia Connect (***)
18. Kia Fan (***)
19. MyKia (***)
20. MyKia Chile (***)
21. Lexus Lounge (****)
22. Lexus Connect (****)
23. MyNISSAN (*****)
24. Nissan Türkiye (*****)
25. My Opel
26. MyPeugeot
27. SEAT Online
28. Maruti Suzuki
29. Yamaha Motor Malaysia

### CODE REVIEW

**Comment by Donnnno** [comment]
Great work again @onuronsekiz ! I've made some modifications, mostly in sizing, but I've simplified some car logo's even more.

With #1804 in mind, I think it's good to think more about our designs, and how we can minify more, and at the same time, keep the right details from the logo's. Let me know what you think. :)

image
image
image

**Comment by Donnnno** [comment]
@TotallyAvailable ah yes, the standouts, that's indeed the beauty of the open-sourceness of the pack. Almost everyone starts contributing because they miss some of their icons. Some even stay to help out with requests, and that's amazing.

**Comment by onuronsekiz** [comment]
More simplified and minifed icons, got it.
I will be more careful with designs next time.
By the way, I am gonna add icons to;

-  _Kia Fan_
- _Kia Connect_
- _Dacia Media Control_

So they won't look same as brand logo.
So please wait while I am working on them.

**Comment by onuronsekiz** [comment]
Uploaded mentioned additions.
It should be ready to merge.

**Comment by Donnnno** [comment]
Great!

**Comment by onuronsekiz** [comment]
Just a quick question, I made some additional car brand logos.
Yet some of them doesn't have an application in Play Store.
Or it is not available for my region so I can't find when I search.
I can't install the application, so I can't get item components.

Can I commit them without appfilter entries or should I ditch them?

**Comment by Donnnno** [comment]
Feel free to add them! Could be useful for in the future, or if people want to apply the icons manually to their setup!

**Pull request merged**
