### PR TITLE
Add chess and checkers icons

### PR DESCRIPTION
**Pull request by austenadler**
WIP: Some unresolved comments:

- [x] Is it fine to use the SVG content from the app repo? It's MIT licensed: https://github.com/jcarolus/android-chess/blob/master/artwork/svg/logo.svg
- [x] Is the checkers logo okay? I removed the bottom right grid since other icons in this pack do not have it.
- [x] @Donnnno not sure which chess variant to go with. In the zip below, I have v1 (true to original icon), v2 (use higher rook border), and v3 (use lower rook border).
- [x] I can also make a v4 that has no border if this would fit better.

[chess-variants.zip](https://github.com/Donnnno/Arcticons/files/5825545/chess-variants.zip)

### CODE REVIEW

**Comment by aaronhatesregex** [comment]
Hi, for chess icon, v2 looks more balanced IMO and you can check out [CONTRIBUTING.md](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md) to improve it.

For checkers logo, please remove the hidden png layer to reduce the size.

**Comment by austenadler** [comment]
Updated with smaller checkers logo.

I also improved the chess logo to match the other icons:
image

**Comment by aaronhatesregex** [comment]
Looks good to me, though there is a transform element I don't know how to delete XD. You may have to wait as @Donnnno has no public activity in the past six days.

**Comment by Donnnno** [comment]
I'm gonna add the pull request and other things this week, had a very busy week, so I didn't have time for that. :)

**Comment by Donnnno** [comment]
Thanks, they look good!

**Pull request merged**
