### PR TITLE
Add 5 icons + update 1 appfilter entry

### PR DESCRIPTION
**Pull request by petlyh**
New icons:
- [FamiStudio](https://play.google.com/store/apps/details?id=org.famistudio)
- [F-Stop](https://play.google.com/store/apps/details?id=com.fstop.photo)
- Hatsune Miku: Colorful Stage! ([English](https://play.google.com/store/apps/details?id=com.sega.ColorfulStage.en) / [Japanese](https://play.google.com/store/apps/details?id=com.sega.pjsekai))
- [Personio](https://play.google.com/store/apps/details?id=com.personio)
- [SnapWidget](https://play.google.com/store/apps/details?id=com.snapwidget.drawing.widgetshare)

Updated appfilter entry:
- [Acode](https://play.google.com/store/apps/details?id=com.foxdebug.acodefree)

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, I messed something up a few days ago, as you can see in the commit history, can you create a new PR again with the changes of this commit? 

Thanks!

**Comment by petlyh** [comment]
Hello, I did a rebase that seems to have fixed this PR. Is it ok for merging now, or do you still want me to create a new PR?

**Comment by Donnnno** [comment]
It's good now! Thanks :)

The icons look great btw!

**Comment by Donnnno** [comment]
Great icons, I merged your two icons already somehow, so they're still in here.

**Pull request merged**
