### PR TITLE
Update FOSS App Icons

### PR DESCRIPTION
**Pull request by xprateek**
- **appfilter.xml**
- **[grayjay](https://grayjay.app/).svg** (FOSS APP)
- **[openlib](https://android.izzysoft.de/repo/apk/com.app.openlib).svg** (FOSS APP)
- **[voyager](https://github.com/aeharding/voyager).svg** (FOSS APP) (Alt Icon*)

image

### CODE REVIEW

**Comment by Donnnno** [comment]
Looks nice!

**Comment by Donnnno** [comment]
Hi! Thanks for your work again.
Noticed that grayjay's icon was unusable again, because of lines that were converted to outlines (fills), also decided to redo the voyager icon because their icon just looks so cute.

image

**Comment by xprateek** [comment]
The voyager icon looks soo amazing

**Comment by Donnnno** [comment]
At a later moment I realised that you can choose different icons, so I'll add your space one back for that one:)

**Pull request merged**
