### PR TITLE
OAndBackupX: Added entry for OAndBackupX v3.0 and removed duplicate

### PR DESCRIPTION
**Pull request by yetanother-user**

### CODE REVIEW

**Comment by Donnnno** [comment]
Why separate them?

**Comment by yetanother-user** [comment]
NeoBackup is a re-brand of OAndBackup, but it has a different name and a different icon.

---

### [OAndBackupX v3.0](https://github.com/NeoApplications/Neo-Backup/releases/tag/3.0.0)
if you download the [apk](https://github.com/NeoApplications/Neo-Backup/releases/download/3.0.0/oabx-release.apk) and extract the icon (res/mipmap-mdpi-v4/ic_launcher.png) you get:

<p align="center"></p>

---

### [NeoBackup v8.1.2](https://github.com/NeoApplications/Neo-Backup/releases/tag/8.1.2)
if you download the [apk](https://github.com/NeoApplications/Neo-Backup/releases/download/8.1.2/Neo_Backup-release.apk) and extract the icon (res/1S.png) you get:

<p align="center"></p>

**Comment by yetanother-user** [comment]
(1) I assigned "ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.IntroActivity}"  (OAndBackupX) to the "oandbackupx" icon.

 (2) "ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.SplashActivity}" (NeoBackup) was associated with two different icons:
```
<!-- Neo Backup / OAndBackupX -->
<item component="ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.SplashActivity}" drawable="oandbackupx" />
<item component="ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.SplashActivity}" drawable="neo_backup" />
```
so I removed the association with the "oandbackupx" icon.

**Comment by Donnnno** [comment]
Sure!

**Pull request merged**
