### PR TITLE
Add Fediverse software and instances

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Adds Fediverse project logos:
- Fediverse
- Firefish
- Akkoma
- GoToSocial
- Pleroma

Adds instance logos:
- SVM
- Infosec
- Tchncs
- Land of Kittens

Aliases logos to instances:
- Mastodon
- Misskey
- Pixelfed

Made with Inkscape, ran through [SVGOMG](https://jakearchibald.github.io/svgomg/)

<table>
<tr>
 <td></td>
<td></td>
<td></td>
<td></td>
<td></td>
 <tr>
 <td></td>
<td></td>
<td></td>
<td></td>
</table>

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
That should be it, sorry for the extra commits.

**Comment by ThatOneCalculator** [comment]
@Donnnno sorry for the extra commits, but should be all good now :+1:

**Comment by Donnnno** [comment]
Akkoma, more like amogus

**Comment by ThatOneCalculator** [comment]
ඞ

**Comment by ThatOneCalculator** [comment]
As per a request, I've added an icon as well for the LoK communities

**Comment by ThatOneCalculator** [comment]
@Donnnno any ETA on this, anything else I should do?

**Comment by Donnnno** [comment]
Did some resizing and made some small changes, so that's all!

**Comment by ThatOneCalculator** [comment]
@Donnnno it seems like the SVM icon got messed up

**Comment by Donnnno** [comment]
oh the original svg was giving me an error too, so I had to convert it again. will check it tomorrow!

**Comment by Donnnno** [comment]
It should be fixed now, there were many double paths in there, so deleted those.

**Comment by ThatOneCalculator** [comment]
Tysm! I had to import that from an Adobe Illustrator file so that's probably why it was weird 🥴

**Pull request merged**
