### PR TITLE
Added 5 icons

### PR DESCRIPTION
**Pull request by toxcien**
Added 5 icons. [AppsMonitor](https://apt.izzysoft.de/fdroid/index/apk/timeline.lizimumu.com.t), [ear (1)](https://play.google.com/store/apps/details?id=com.nothing.smartcenter), [MTV Katsomo](https://play.google.com/store/apps/details?id=fi.mtvkatsomo), [Aethersx2](https://play.google.com/store/apps/details?id=xyz.aethersx2.android) and [Arx Control](https://play.google.com/store/apps/details?id=com.logitech.gaming.arxcontrolapp).

Edit: I hope I did everything correctly

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi! Thanks for the icons, can you gather the corresponding data and paste it in the appfilter.xml? 
https://github.com/Kaiserdragon2/IconRequest

Also can you rename ear(1) to ear_1?

**Comment by toxcien** [comment]
Data has been now pasted to appfilter.xml and renamed the ear (1) to ear_1

**Comment by Donnnno** [comment]
great

**Comment by Donnnno** [comment]
Hi! I;ve taken a closer look at the icons and found some inconsistencies:

image

Make sure that the line width is the same for every icon (1px or pt) 

also, some shapes were very messy, try to avoid clipping masks:

image

**Pull request merged**
