### PR TITLE
8 new icons

### PR DESCRIPTION
**Pull request by Quantenzitrone**
I put the icons in /other and updated the appfilter.xml file.

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, thanks for your pull request. 
The icons look good from what I've seen with a first glance.

Will take a better look later.

Try to put everything in alphabetic order in the appfilter next time. That saves me some time :^)

**Comment by Donnnno** [comment]
Hi, I've taken a better look and have a couple of points for next time.

Most things are in the contribution image [here](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md)
- I noticed that some icons had a brown fill with 0% opacity.
- Fills in general (except for dots) aren't allowed in the icons
- lines should always be 1 px of pt
- don't stretch or squash letters! 

A screenshot of the changes, top: old, bottom: new:

image

Besides that, everything was good. They will appear in the next update!

**Comment by Quantenzitrone** [comment]
I just realized the .svg from the app de-bloater contains a - in the file name which you specifically asked it not to have. I hope that  doesn't cause any issues.

**Comment by Donnnno** [comment]
I just fixed that :) no worries
Its something that causes the app to crash :s

**Pull request merged**
