### PR TITLE
Add Soundbound Icon

### PR DESCRIPTION
**Pull request by Subroutine7901**
Just adds an icon for the app Soundbound (in.shabinder.soundbound).

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, you also need to add some lines of code to the appfilter.xml file, otherwise it won't get applied. 
You can gather it with icon request: https://play.google.com/store/apps/details?id=de.kaiserdragon.iconrequest

**Comment by Subroutine7901** [comment]
Ok so here's the code, I'm just putting this here so I don't forget or lose it:
`<appfilter>

<item component="ComponentInfo{in.shabinder.soundbound/in.shabinder.soundbound.MainActivity}" drawable="soundbound"/>
</appfilter>`
Otherwise, a quick rundown of what I need to do with the modified appfilter.xml, and the required edits to it would be appreciated.

**Comment by Subroutine7901** [comment]
Ok, I think that's it.

**Comment by Donnnno** [comment]
Fantastic, thank you, and @TotallyAvailable for helping out :)

**Pull request merged**
