### PR TITLE
Added BNH BeMobile and TKCompanionApp and added my name to contributers

### PR DESCRIPTION
**Pull request by Calciume**

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi! 

Can you replace the capital letters in the files with normal lowercase ones?

**Comment by Calciume** [comment]
I think I fixed it, this is my first time using Github sorry

**Comment by Donnnno** [comment]
no problem, thanks!

**Comment by Donnnno** [comment]
Try to take a look at the template files for sizing! Other than that, great work~!

**Pull request merged**
