### PR TITLE
Add Infinitode 2's icon

### PR DESCRIPTION
**Pull request by andmagdo**

### CODE REVIEW

**Comment by andmagdo** [comment]
uhh, oops--lemme remake this pull-I have no clue why it put 380 commits

**Comment by Donnnno** [comment]
Sorry! This was my fault... Messed it up huge yesterdat, but everything is good again

**Comment by andmagdo** [comment]
Yeah, no worries. I recreated the request over at #1263

**Comment by Donnnno** [comment]
Yeah, thanks!

**Pull request closed without merging**
