### PR TITLE
10 new icons added

### PR DESCRIPTION
**Pull request by fakegamer666**
Hello,
I like this icon pack and your work, so I just created some missing icons. Will add some more later.
Hopefully I got everything right according to the guide.

de.blitzer.plus
de.blitzer.activity.SplashScreen

de.corona.tracing.m_vap
de.rki.coronawarnapp.ui.launcher.LauncherActivity

de.dwins.financeguru
de.dwins.financeguru.SplashActivity

de.materna.bbk.mobile.app
de.materna.bbk.mobile.app.ui.SplashScreenActivity

com.pr0gramm.app
com.pr0gramm.app.ui.MainActivity

com.oceanwing.soundcore
com.oceanwing.soundcore.activity.WelcomeActivity

com.storz_bickel.app.m_vap
com.storz_bickel.app.sbapp.StartActivity

de.koloch.evaluator.free.app
de.koloch.evaluator.free.MainActivity

de.dwd.warnapp
de.dwd.warnapp.base.MainActivity

fm.weareone.player.app
fm.weareone.player.MainActivity

Added all missing activity names.

### CODE REVIEW

**Comment by Donnnno** [comment]
Looks good! But I need the full activity names. You can gather them with the turtl app mentioned in the readme :)

**Comment by Donnnno** [comment]
Thanks for adding the names, but use Turtl to collect the names in the future and send them like this, thanks it saves a lot of time for me:
```
<!-- Corona Tracing -->
<item component="ComponentInfo{de.corona.tracing.m_vap/de.rki.coronawarnapp.ui.launcher.LauncherActivity}" drawable="coronatracing"/>
```

**Comment by fakegamer666** [comment]
Thank you for your feedback. I just added 11 new icons and provided the names collected by Turtl.

**Comment by Donnnno** [comment]
Thanks!



<item component="ComponentInfo{com.rascarlo.adaptive.brightness.tile/com.rascarlo.adaptive.brightness.tile.MainActivity}" drawable="adaptivebrightnesstile"/>

<item component="ComponentInfo{com.minar.birday/com.minar.birday.activities.SplashActivity}" drawable="birday"/>

<item component="ComponentInfo{btools.routingapp/btools.routingapp.BRouterActivity}" drawable="brouter"/>

<item component="ComponentInfo{com.dev47apps.droidcam/com.dev47apps.droidcam.DroidCam}" drawable="droidcam"/>

<item component="ComponentInfo{com.concept1tech.instalate/com.concept1tech.instalate.PrefsActivity}" drawable="instalateeinstellungen"/>

<item component="ComponentInfo{de.lennartz.muellweg/inputfilesample.android.chrome.google.com.inputfilesample.SplashScreen}" drawable="mllwegde"/>

<item component="ComponentInfo{de.storchp.opentracks.osmplugin/de.storchp.opentracks.osmplugin.MainActivity}" drawable="osmdashboardfropentracks"/>

<item component="ComponentInfo{com.psperl.prjM/com.psperl.prjM.MainActivity}" drawable="projectm"/>

<item component="ComponentInfo{com.rohit2810.spotit/com.rohit2810.spotit.SplashActivity}" drawable="spotit"/>

<item component="ComponentInfo{de.blau.android/de.blau.android.Splash}" drawable="vespucci"/>

<item component="ComponentInfo{com.xBrowserSync.android/com.xBrowserSync.android.MainActivity}" drawable="xbrowsersync"/>

**Comment by Donnnno** [comment]
Can you give me the appnames of these apps:

```
de.blitzer.plus
de.blitzer.activity.SplashScreen

de.corona.tracing.m_vap
de.rki.coronawarnapp.ui.launcher.LauncherActivity

de.dwins.financeguru
de.dwins.financeguru.SplashActivity

de.materna.bbk.mobile.app
de.materna.bbk.mobile.app.ui.SplashScreenActivity

com.pr0gramm.app
com.pr0gramm.app.ui.MainActivity

com.oceanwing.soundcore
com.oceanwing.soundcore.activity.WelcomeActivity

com.storz_bickel.app.m_vap
com.storz_bickel.app.sbapp.StartActivity

de.koloch.evaluator.free.app
de.koloch.evaluator.free.MainActivity

de.dwd.warnapp
de.dwd.warnapp.base.MainActivity

fm.weareone.player.app
fm.weareone.player.MainActivity
```

**Comment by Donnnno** [comment]
Congrats on your first submission to the Arcticons project, your icons are looking great, I just made some small adjustments :)
If you can give me the names of the apps I can complete this pull request!

**Comment by fakegamer666** [comment]
Thanks for your feedback. Are these small adjustments I could do by myself next time?

There you go:


<item component="ComponentInfo{de.blitzer.plus/de.blitzer.activity.SplashScreen}" drawable="blitzer.deplus"/>


<item component="ComponentInfo{de.corona.tracing/de.rki.coronawarnapp.ui.launcher.LauncherActivity}" drawable="coronatracing"/>


<item component="ComponentInfo{de.dwins.financeguru/de.dwins.financeguru.SplashActivity}" drawable="finanzguru"/>


<item component="ComponentInfo{de.materna.bbk.mobile.app/de.materna.bbk.mobile.app.ui.SplashScreenActivity}" drawable="nina"/>


<item component="ComponentInfo{com.pr0gramm.app/com.pr0gramm.app.ui.MainActivity}" drawable="pr0gramm"/>


<item component="ComponentInfo{com.oceanwing.soundcore/com.oceanwing.soundcore.activity.WelcomeActivity}" drawable="soundcore"/>


<item component="ComponentInfo{com.storz_bickel.app.m_vap/com.storz_bickel.app.sbapp.StartActivity}" drawable="storzbickel"/>


<item component="ComponentInfo{de.koloch.evaluator.free/de.koloch.evaluator.free.MainActivity}" drawable="verkaufswertrechnerfree"/>


<item component="ComponentInfo{de.dwd.warnapp/de.dwd.warnapp.base.MainActivity}" drawable="warnwetter"/>


<item component="ComponentInfo{fm.weareone.player/fm.weareone.player.MainActivity}" drawable="weareone"/>

**Review by fakegamer666 — COMMENTED** [review]
<item component="ComponentInfo{de.blitzer.plus/de.blitzer.activity.SplashScreen}" drawable="blitzer.deplus"/>

<item component="ComponentInfo{de.corona.tracing/de.rki.coronawarnapp.ui.launcher.LauncherActivity}" drawable="coronatracing"/>

<item component="ComponentInfo{de.dwins.financeguru/de.dwins.financeguru.SplashActivity}" drawable="finanzguru"/>

<item component="ComponentInfo{de.materna.bbk.mobile.app/de.materna.bbk.mobile.app.ui.SplashScreenActivity}" drawable="nina"/>

<item component="ComponentInfo{com.pr0gramm.app/com.pr0gramm.app.ui.MainActivity}" drawable="pr0gramm"/>

<item component="ComponentInfo{com.oceanwing.soundcore/com.oceanwing.soundcore.activity.WelcomeActivity}" drawable="soundcore"/>

<item component="ComponentInfo{com.storz_bickel.app.m_vap/com.storz_bickel.app.sbapp.StartActivity}" drawable="storzbickel"/>

<item component="ComponentInfo{de.koloch.evaluator.free/de.koloch.evaluator.free.MainActivity}" drawable="verkaufswertrechnerfree"/>

<item component="ComponentInfo{de.dwd.warnapp/de.dwd.warnapp.base.MainActivity}" drawable="warnwetter"/>

<item component="ComponentInfo{fm.weareone.player/fm.weareone.player.MainActivity}" drawable="weareone"/>

**Comment by Donnnno** [comment]
Hi these are the things I changed most changes are there to unify the icons.

Birday: connected the lines
image

Droidcam: used an existing android icon to make it more consistent.
image

InstaLate: replaced the letters with a modified version of the arcticons font
image

ProjectM: better kerning and made it slightly larger by putting the M below 'project'
image

(I forgot the appname) but replaced it with the standard dollar icon :) 
image

Warnwetter: remove the letters the icon should already be recognizable without the letters.
image


I hope you can agree with these changes and if you don't just let me know ;)

**Comment by Donnnno** [comment]
Where can I see the names?

**Comment by Donnnno** [comment]
Can you just put them in the comments here? :)

**Comment by fakegamer666** [comment]
Yes, I fully agree. Looks a lot cleaner after your edits now!

Somehow I am unable to put the names into my comment, also can't edit older comments to show them. Don't know what I am doing wrong. It's weird. I guess it's because of the formatting. I just removed the characters and didn't touch the names from Turtl. Sorry for this inconvenience :/

Blitzer.de PLUS
Corona Tracing
Finanzguru
NINA
pr0gramm
Soundcore
STORZ & BICKEL
Verkaufswert Rechner FREE
WarnWetterWe aRe oNe

**Comment by Donnnno** [comment]
That's no problem, these things can be quite dificult sometimes, Thanks

**Comment by Donnnno** [comment]
That's it! Just gonna raster all the icons and then put the next update online.

**Comment by Donnnno** [comment]
I published the update, you can download the APK here or wait probably something like for it to arrive on F-Droid.

**Pull request merged**
