### PR TITLE
4 logos

### PR DESCRIPTION
**Pull request by Juvss**
Here are 4 logos I made

Super auto pets is a strategy game
pets

Planes android is a battleship-like game on the fdroid repository
plane

Pixel artist is also on fdroid and it's a pixel art editor
pixel

Fender tune is a tuner for string instruments made by fender
tuner

This is my first contribution and I didn't understand the bit about actions, but here are the labels that appear when looking at app info
Super auto pets: com.teamwood.spacewood.unity
Planes android: com.planes.android
Pixel artist: rodrigodavy.com.github.pixelartist
Fender tune: com.fender.tuner

Also, when looking for apps that didn't have an icon I saw one that was just a star and another that was a note taking one, but I figured those were too simple to make. So I was wondering if it was possible to add a "general" section for simple shapes or default apps to make those kind of replacements without having to make a specific icon for them, kinda like the letters and numbers sections.

### CODE REVIEW

**Comment by Donnnno** [comment]
These icons are really nice! I like the cute turtle! 

> Super auto pets: com.teamwood.spacewood.unity
Planes android: com.planes.android
Pixel artist: rodrigodavy.com.github.pixelartist
Fender tune: com.fender.tuner


Can you use the [turtl app](https://f-droid.org/en/packages/org.xphnx.iconsubmit/) to gather the data and paste it here, or in the [appfilter here](https://github.com/Donnnno/Arcticons/blob/main/other/appfilter.xml).

> Also, when looking for apps that didn't have an icon I saw one that was just a star and another that was a note taking one, but I figured those were too simple to make. So I was wondering if it was possible to add a "general" section for simple shapes or default apps to make those kind of replacements without having to make a specific icon for them, kinda like the letters and numbers sections.

I'm working on a general set of icons atm :^) 

Oh and one last thing: Can you remove the uppercase letters in the filenames? It makes the app crash :s 

Thanks!

**Comment by Juvss** [comment]
super auto pets: com.teamwood.spacewood.unity/com.unity3d.player.UnityPlayerActivity
planes android: com.planes.android/com.planes.android.PlanesAndroidActivity
pixel artist: rodrigodavy.com.github.pixelartist/rodrigodavy.com.github.pixelartist.MainActivity
fender tune: com.fender.tuner/com.fender.tuner.activities.HomeActivity

I wasn't able to get a document from turtl so I don't know if there is information missing. And for adding it to the appfilter if I do this again, is it just putting that in <item component="{name of activity}" drawable="name of app" />? and should it be in alphabetical order along with the rest or in the end so its easier to find?

**Comment by Donnnno** [comment]
If you select the first option for gathering icons, it should be copied to your clipboard!

**Comment by Juvss** [comment]
Thank you! here it is


<item component="ComponentInfo{com.fender.tuner/com.fender.tuner.activities.HomeActivity}" drawable="fendertune"/>

<item component="ComponentInfo{rodrigodavy.com.github.pixelartist/rodrigodavy.com.github.pixelartist.MainActivity}" drawable="pixelartist"/>

<item component="ComponentInfo{com.planes.android/com.planes.android.PlanesAndroidActivity}" drawable="planesandroid"/>

<item component="ComponentInfo{com.teamwood.spacewood.unity/com.unity3d.player.UnityPlayerActivity}" drawable="superautopets"/>

**Pull request merged**
