### PR TITLE
Chiki Chiki Tube 

### PR DESCRIPTION
**Pull request by ourslfs**
tube.chikichiki.sako

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
Just an Info you only need to do the white version of the icon the black version is generated by a Script.

**Comment by Donnnno** [comment]
Also, your SVG contains an image right now, you should delete that part :)

And can you put the code inside the appfilter.xml in /other?

You can gather it with icon request: https://github.com/Kaiserdragon2/IconRequest/releases

**Comment by ourslfs** [comment]
I've fixed the icon, but github is stuck at "processing your files"...

**Comment by ourslfs** [comment]
chikichiki

**Comment by Donnnno** [comment]
Great, thanks!

**Pull request merged**
