### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by Lelio-Brun**
Hello, here are 2 new icons, plus an alternative activity name for an existing one.

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, thanks for your PR. It looks good!
Planning to release the next update somewhere this weekend or next week.

**Comment by Donnnno** [comment]
Oh, but please leave them in the `/other` folder, that makes it easier for me to keep track of the new icons ;)

**Comment by Lelio-Brun** [comment]
Oh sorry I forgot that!

**Comment by Donnnno** [comment]
No worries :^)

**Pull request merged**
