### PR TITLE
added 6 icons

### PR DESCRIPTION
**Pull request by basings**
collage_maker_gridart
fitpix_collage
incollage_collage_maker
layout
photo_collage
piccollage

### CODE REVIEW

**Comment by basings** [comment]
I'm not sure if I created the pull request properly because the commits of #1239 are in this PR included . If not, let me know.

**Comment by Donnnno** [comment]
Hi there are a lot of conflicts with the appfilter, can you rebase?

Also can you put your created icons in the other folder? thanks!

**Comment by Donnnno** [comment]
hey, you're missing the appfilter lines for all the icons you made!

**Comment by Donnnno** [comment]
I've cleaned up some parts of the svg's and noticed there are like 3 of the same icons, when you add the xml lines, you can give the drawable name part the "layout" name.

**Pull request closed without merging**
