### PR TITLE
Updates to appfilter.xml, to fix broken icons.

### PR DESCRIPTION
**Pull request by dalaeance**
I had opened an issue about the changes I think need to be made to fix some icons that aren't working. But then I wondered what would happen if I tried to edit the file directly. Hahaha! I'm learning GitHub!!

Here's the issue referenced: https://github.com/Donnnno/Arcticons/issues/1182

### CODE REVIEW

**Comment by dalaeance** [comment]
Into which version would my suggestions (have) be(en) merged? 4.2.8 came out after my suggestions were seemingly accepted, but only 2 of the 5 apps' icons were fixed. The icons for Feeld, Medito, and NFC Tools are still not working.

**Comment by Donnnno** [comment]
I'll take a look :)

**Comment by Donnnno** [comment]
I think for some reason the lines were removed, probably in a merge conflict. Anyways I've added them again.

**Comment by dalaeance** [comment]
Thanks, Donno!

**Pull request merged**
