### PR TITLE
41 new icons

### PR DESCRIPTION
**Pull request by filipkemuel**
Hi, I wanted to contribute so this is my first contribution.

I made 41 new icons:
Apoteket - https://play.google.com/store/apps/details?id=dk.apotekerforeningen.apoteksapp
Auphonic Edit - https://play.google.com/store/apps/details?id=com.auphonic.auphonicrecorder
Biblioteket - https://play.google.com/store/apps/details?id=app.redia.dk.biblioteket
Bilka Plus - https://play.google.com/store/apps/details?id=dk.bilka.app.release
Bilka ToGo - https://play.google.com/store/apps/details?id=dk.dsg.bilkatogo
Bilka Scan&Go - https://play.google.com/store/apps/details?id=dk.dsg.scanandgo.bilka
BubbleUPnP - https://play.google.com/store/apps/details?id=com.bubblesoft.android.bubbleupnp
Check Udvej - https://play.google.com/store/apps/details?id=dk.rejsekort.checkudvej
Chord Analyser - https://play.google.com/store/apps/details?id=com.pragmatic.apps.piano.chord.analyser
Churchdesk - https://play.google.com/store/apps/details?id=com.churchdesk
Coronapas - https://play.google.com/store/apps/details?id=dk.sum.ssicpas
Dankort - https://play.google.com/store/apps/details?id=eu.nets.dankort
DBA - Den Blå Avis - https://play.google.com/store/apps/details?id=dk.dba.android
DO Swimmer - https://play.google.com/store/apps/details?id=com.yassirh.digitalocean
e-Boks.dk - https://play.google.com/store/apps/details?id=com.eboks.activities 
eReolen - https://play.google.com/store/apps/details?id=dk.redia.eReolen
Flextrafik - https://play.google.com/store/apps/details?id=dk.flexdanmark.flextrafik
floccus - https://play.google.com/store/apps/details?id=org.handmadeideas.floccus
Freetrailer - https://play.google.com/store/apps/details?id=com.freetrailer
GLS Denmark - https://play.google.com/store/apps/details?id=dk.gls.consigneeapp
Gods DJs Radio - https://play.google.com/store/apps/details?id=com.godsdjsradio
Godt Smil - https://play.google.com/store/apps/details?id=dk.godtsmil.gsapp
Jyske Bank - https://play.google.com/store/apps/details?id=dk.jyskebank.drb
Jyske Bank: Mine Kort - https://play.google.com/store/apps/details?id=dk.jyskebank.cardapp
Kørekort - https://play.google.com/store/apps/details?id=dk.digst.mdl
Medicinkortet - https://play.google.com/store/apps/details?id=com.trifork.medicinkortet
Min Læge - https://play.google.com/store/apps/details?id=com.trifork.minlaege
MitID - https://play.google.com/store/apps/details?id=dk.mitid.app.android
Mobilklinik - https://play.google.com/store/apps/details?id=com.trifork.medical.mobilklinik
Netto+ - https://play.google.com/store/apps/details?id=dk.dsg.netto
NORMAL - https://play.google.com/store/apps/details?id=dk.normal.normal
Nærboks - https://play.google.com/store/apps/details?id=com.swipbox.infinity.consignee_app
PostNord - https://play.google.com/store/apps/details?id=se.postnord.private
Pushover - https://play.google.com/store/apps/details?id=net.superblock.pushover
Rejsekort Status - https://play.google.com/store/apps/details?id=dk.rejsekort.rejsekortstatus
Rema1000 - https://play.google.com/store/apps/details?id=dk.iroots.rema1000
Remarkable - https://play.google.com/store/apps/details?id=com.remarkable.mobile
Sectograph - https://play.google.com/store/apps/details?id=prox.lab.calclock
SQ4You - https://play.google.com/store/apps/details?id=com.allenheath.SQU.You
SQ MixPad - https://play.google.com/store/apps/details?id=com.allenheath.squmixpad
WeShare - https://play.google.com/store/apps/details?id=com.danskebank.weshare

### CODE REVIEW

**Comment by Donnnno** [comment]
41! That's huge! wow

Gonna take a better look at this later :)

**Comment by Donnnno** [comment]
Small tip for the next time: You can just put all the appfilter data at the beginning or end on the list, saves a lot of time!

I sort the list with every release :)

**Comment by filipkemuel** [comment]
Okay.. Will do.. :)

**Comment by Donnnno** [comment]
I'm going trough every icon right now and after that I'm merging your PR!

**Comment by Donnnno** [comment]
Hi! I've merged your PR and changed some stuff here and there. 

There are some small visual changes to make it more Arcticons here and there. 

You've made a lot of great icons!

**Pull request merged**
