### PR TITLE
Add additional SVGs

### PR DESCRIPTION
**Pull request by Saijin-Naib**
On-going work adding additional SVGs for Arcticons.

### CODE REVIEW

**Comment by Donnnno** [comment]
Great, but I noticed the artboard size of your target icon is really weird:
   viewBox="0 0 210 297"
   height="297mm"
   width="210mm">

**Comment by Saijin-Naib** [comment]
> Great, but I noticed the artboard size of your target icon is really weird:
> viewBox="0 0 210 297"
> height="297mm"
> width="210mm">

I have no idea what that means 🤣

I'm using the frost template, and scaling the SVGs to fill the boundary of the Square template before I save them out. I did the same thing for the prior icons I submitted.

Is that wrong?

**Comment by Donnnno** [comment]
It should be 48 x48

**Comment by Saijin-Naib** [comment]
> It should be 48 x48

Are what I submitted unacceptable? Or is this just something to correct moving forward?

**Comment by Donnnno** [comment]
Oh no worries, I can fix it myself too. The document size is just really weird. Nothing unacceptable tho.

**Comment by Donnnno** [comment]
This is what I'm talking about: the big rectangle is the artboard size:

image

**Comment by Saijin-Naib** [comment]
This is what I see in my InkScape Document Properties for the main project file I work on, which I attached above (arcticons_square):  
image

That is the expected value of 48x48, correct? I wonder if InkScape adjusts the document size to A4 when I Save As plain SVG instead of the InkScape SVG I'm editing in.

**Comment by Donnnno** [comment]
Yeah, that might be possible, the other icons are fine tho!

**Comment by Saijin-Naib** [comment]
> Yeah, that might be possible, the other icons are fine tho!

My InkScape auto-updates, so maybe this behavior changed from the earlier icons and after the update... Hmm.

I can't seem to get the canvas size to stick after exporting to plain SVG

**Comment by Saijin-Naib** [comment]
I think I'm at a good stopping point for now, if these are acceptable for you.

**Comment by Donnnno** [comment]
Can you provide the lines of code in one xml file, like how turtl does it?

**Comment by Saijin-Naib** [comment]
I've attached the edited XML from TURTL (empty,xml):  
[10_icons.zip](https://github.com/Donnnno/Arcticons/files/6164216/10_icons.zip)

Please let me know if this is what you need.

**Comment by Donnnno** [comment]
Just merged it and checked the icons, be sure to use the 1pt/px line thickness :)

**Pull request merged**
