### PR TITLE
Android studio svg to xml convert

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Convert Svgs at build time to xml drawables with android studios built in converter
add xml icon support for light and dark(disabled for now)
fix clock color in light
move some drawables (drawables that aren't icons are now all in one place /drawables for each version)

### CODE REVIEW

**Comment by Donnnno** [comment]
Dark/Light are not XML because some popular launchers don't support that format. I'd rather keep it that way for now.

**Comment by Kaiserdragon2** [comment]
I can disable that option.
Could you give me some examples which launchers don't support it. i would like to test these.

**Comment by Kaiserdragon2** [comment]
Mostly generating the xml icons is much faster then the png when generating the release also the file size is much smaller. Generating all 8000 icons for the you version takes on my pc arround 20 seconds for the png it takes for just a few icons over a minute.

**Comment by Kaiserdragon2** [comment]
i don,t even think that xml icons will make any problems on any launcher because the drawables are handled by android it self in most cases.

**Comment by Donnnno** [comment]
Probably gonna postpone this till MS Launcher gets their shit together

**Comment by xprateek** [comment]
better to create new dev branch soo new variant SVG → XML  keep updating during Christmas time.

AS Microsoft Being Microsoft they only change when required....

**Pull request closed without merging**
