### PR TITLE
Colors theme, description and icon name

### PR DESCRIPTION
**Pull request by Aman9das**
polished a bit, you can change the graphics at the navigation view, and the about screen

### CODE REVIEW

**Comment by Aman9das** [comment]
If you want you can change the description format from unordered list to paragraphs..

remove <ul> and replace <li> with <p>

**Comment by Donnnno** [comment]
Wow! These changes are great! Gonna take a look at them right now!

**Comment by Donnnno** [comment]
The super raster is great, but it's missing some steps, I think. I don't know how these shell scipts work, tho. When I tested it with a normal icon in other, it creates a black icon and generates the drawable.xml & iconpack.xml.

image

I think it has to follow these steps: 

- raster files in other to `/dark/res/drawable-nodpi`
- make a copy of the white svg's in `/other` and copy them to `icons/white`
- then convert the icons in `/other` to black and use the rasterlight.sh to do the same trick but to `/light/res/drawable-nodpi`
- and then move the black svg's to `icons/black`
- last step: generate the drawable & iconpack xml's

**Comment by Aman9das** [comment]
Acrylicicons was already there in dark mode drawable-nodpi what did you expect to change, huh? Throw a random new svg at it.. and it will show the difference properly

**Comment by Donnnno** [comment]
oh right haha! whoops!

**Comment by Donnnno** [comment]
Okay, I was stupid for a sec, this works really great!!!!

**Comment by Donnnno** [comment]
Btw, is it possible to add an extra step in xml.sh to copy the appfilter.xml & drawable.xml files from `main/values` to `main/res/xml`?

**Comment by Aman9das** [comment]
No it does'nt yet. It just deletes the name attribute of the drawable.svg file.. i had written <picture="a2048" name="2048"> but the rebuilding drawable.xml part undoes all of it, not a big deal though, no one looks at the drawable display name.

Yes sure ... I'll do that tonight

**Comment by Aman9das** [comment]
Please check do check the icon request issue which you had closed.. great news there..

**Pull request merged**
