### PR TITLE
Update some icons 

### PR DESCRIPTION
**Pull request by prateekmaru**
Screenshot_20231004-173659_DroidX-UI Launcher 
Screenshot_20231004-173017_DroidX-UI Launcher
Screenshot_20231004-172835_DroidX-UI Launcher

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi! Thanks a lot for your contribution. Looks good, but can you put the new icons only in the `/other` folder, as explained in the contribution file? :)

**Comment by prateekmaru** [comment]
Yes, i read the guidelines i compiled because I'm just checking if the icons are not properly made I'll update the `/other/xprateek` folder ASAP with all *.svg 

Thanks 
Prateek Maru

**Comment by Donnnno** [comment]
Great that you've tested them! But no need to merge make a PR for that, I check every icon when I go through a PR and make sure it fits in the pack with small modifications. 

So I only need the SVGs and appfilter entries!

**Comment by prateekmaru** [comment]
yes totally agree! close this PR I'll fork new and merge only `*.svg` && `appfilter.xml`
in `other/username` folder 📁 as per guidelines in next **PR**

Thanks

**Pull request closed without merging**
