### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by onuronsekiz**
57 new app icons. (*4 is appfilter entry)
2 previous uploaded icons revised.

Uploaded:

1. A101
2. Anadolujet
3. Bein Connect Türkiye *
4. Beymen
5. Bim
6. Bitaksi
7. Boyner
8. CarrefourSA
9. Cepte Şok
10. Çiçeksepeti
11. Cimri
12. D&R
13. Daha Daha
14. Decathlon Türkiye *
15. DeFacto
16. Dolap
17. Dominos
18. English Home
19. Enpara
20. Enterprise Türkiye
21. Enuygun
22. Flo Türkiye
23. Getir
24. Gratis
25. Hangi Kredi
26. Hepsiburada
27. Hopi
28. Ikea Türkiye *
29. Ing Mobil *
30. İşCep
31. İsteGelsin
32. KFC Türkiye
33. Koçtaş
34. Koton
35. Kuveyt Turk
36. LC Waikiki
37. Letgo
38. Maçkolik
39. Metro Market Türkiye
40. Migros
41. Mobil Deniz
42. Morhipo
43. N11
44. Obilet
45. Papara
46. Paribu
47. Pegasus Airlines
48. PttAVM
49. Qnb Finansbank
50. Sahibinden
51. Sixt
52. Teknosa
53. Tıkla Gelsin
54. Turkcell TV+
55. Turkish Airlines
56. Yemeksepeti
57. Yolcu360

Revised:

1. Ego Cep'te
2. Vakifbank

### CODE REVIEW

**Comment by Donnnno** [comment]
Wow, so many icons! Great work

**Comment by onuronsekiz** [comment]
Thanks, these are probably most downloaded and used apps in Turkey.
I also committed some error corrections and simplifications.

**Comment by Donnnno** [comment]
It's always nice to see Arcticons getting some good coverage in more places in the world, so thanks for doing it for Türkiye!

**Comment by onuronsekiz** [comment]
I really didn't like some filesizes and designs.
Sorry for huge updates, I had to rework them.
Gonna be more careful next time before uploading.

**Comment by Donnnno** [comment]
I've made some small changes, mostly text related stuff for consistency, other than that, outstanding work!

**Comment by onuronsekiz** [comment]
I have no complaints with your changes except _bim.svg_
Original icon's dent at top is not horizontally aligned.
It looks a bit better if text is aligned centered.
And dent has to be a little left on top of letter I.

**Comment by Donnnno** [comment]
Oh I think I forgot to add your latest change for Bim then, can you add it again? Sorry

**Pull request merged**
