### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
As per request, all icons going forward (although I'm unsure if I'll submit more) will go here. Feel free to merge at any time, as if I do end up adding more icons I'll make another PR.

New icons:

- Firstent Mobile
- Metrolink
- Miitomo

Changed icons:

- Termux (new logo)
- Yet Another Call Blocker (spacing was off)

Removed icons:

- Fairemail (generic `mail` fits current icon far better)

<table>
<tr>
<td></td>
<td></td>
<td></td>
<tr>
<td></td>
<td></td>
</table>

### CODE REVIEW

**Comment by Donnnno** [comment]
No need to update the stuff in /assets and /res, that happens automatically!

**Comment by Donnnno** [comment]
Due to merging errors, and my incompetence to figure it out, I’ve added your icons in a different commit, see ^

**Comment by ThatOneCalculator** [comment]
Ah, gotcha. I'll keep that in mind for the future. Thank you!

**Comment by Donnnno** [comment]
But I forgot to say: Great work!

**Pull request closed without merging**
