### PR TITLE
Fixed some svg not respecting the format

### PR DESCRIPTION
**Pull request by tieu1991**
These svg had some fill and stroke not exactly white. (eg. was fdfdfd instead of fff). This was causing the rasterlight to generate partialy white icons instead of all black.

### CODE REVIEW

**Comment by tieu1991** [comment]
Will I found these I noticed that some icons in app\src\light\res\drawable-nodpi were white instead of black. There are no svg files for those png:
- clock_bg
- clock_digital_widget_preview
- clock_hour
- clock_minute
- clock_widget_preview
- date_widget_preview
- habitica
- qmanager
- wherebydate

**Comment by Kaiserdragon2** [comment]
fixed some of these in #1168 
- habitica
- qmanager
- whereby

**Comment by Kaiserdragon2** [comment]
The clock and date related pngs are colorwise fine there are just no svgs  or am I missing something ?

**Comment by Donnnno** [comment]
Clocks don't need svgs:)

**Comment by tieu1991** [comment]
I noticed this when I tried to generate another color version of the app. When I ran a modified version of raster.sh the clocks png were not overwritten to the new color because there was no svg to regenerate it. It is not really a problem for what I was trying to do. I was just wondering if it was normal.

**Comment by Donnnno** [comment]
Now that you mention it, I still can upload it when i have time. It's a nice to have feature.

**Pull request merged**
