### PR TITLE
added 36 icons

### PR DESCRIPTION
**Pull request by joelchrono12**
Here are some icons!

showcase

### CODE REVIEW

**Comment by joelchrono12** [comment]
More icons! 
showcase

**Comment by joelchrono12** [comment]
Icons again
showcase

**Comment by joelchrono12** [comment]
Added some more icons
showcase

**Comment by Donnnno** [comment]
Planning to add these somewhere later today :)

**Comment by joelchrono12** [comment]
Icons for #725 :P 
showcase

**Comment by joelchrono12** [comment]
Some more icons added!
showcase

**Comment by joelchrono12** [comment]
Yet another group of icons :P
showcase

**Pull request merged**
