### PR TITLE
Icons and appfilter info for Issue #160

### PR DESCRIPTION
**Pull request by greenpeteuk**
Four icons for Issue/icon request #160 and appfilter code.
These icons were tricky and I'm not sure how good they are. Please make sure to check them.

### CODE REVIEW

**Comment by Donnnno** [comment]
Looks very good!
The basic shapes around the icons are a bit unnecessary, you can remove those :^) 
Thanks!

**Comment by greenpeteuk** [comment]
Do you mean remove the 'basic shapes' on all of them?
This would, I feel mean that the main content would then need enlarging, yes?

**Comment by greenpeteuk** [comment]
I have changed the icons for this pull request and pushed them to my remote. I believe you should now be able to see the changes.

**Comment by Donnnno** [comment]
Great work again :^)
Thanks!

**Pull request merged**
