### PR TITLE
Update 25 Icons

### PR DESCRIPTION
**Pull request by xprateek**
- appfilter.xml
- [bhagavad\_gita](https://www.f-droid.org/packages/com.wirelessalien.android.bhagavadgita/).svg
- [canta](https://apt.izzysoft.de/fdroid/index/apk/org.samo_lego.canta).svg
- [commandclick](https://apt.izzysoft.de/fdroid/index/apk/com.puutaro.commandclick).svg
- [diary\_vault](https://apt.izzysoft.de/fdroid/index/apk/me.sankethbk.dairyapp).svg
- [formsapp](https://play.google.com/store/apps/details?id=com.heartfull.forms&pcampaignid=web_share).svg
- [fulguris](https://play.google.com/store/apps/details?id=net.slions.fulguris.full.playstore&pcampaignid=web_share).svg
- [fulguris\_foss](https://www.f-droid.org/packages/net.slions.fulguris.full.fdroid/).svg
- [geomag](https://apt.izzysoft.de/fdroid/index/apk/com.sanmer.geomag).svg
- [gopeed](https://gopeed.com/).svg
- [graded](https://www.f-droid.org/packages/com.NightDreamGames.Grade.ly/).svg
- [hdo\_box](https://hdobox.github.io/).svg
- [inventory](https://www.f-droid.org/packages/com.codelv.inventory/).svg
- [kanji\_dojo](https://www.f-droid.org/packages/ua.syt0r.kanji.fdroid/).svg
- [kpassnotes](https://www.f-droid.org/packages/com.ivanovsky.passnotes/).svg
- [nozzle](https://apt.izzysoft.de/fdroid/index/apk/com.dluvian.nozzle).svg
- [pinkt](https://apt.izzysoft.de/fdroid/index/apk/com.fibelatti.pinboard).svg
- [primal](https://apt.izzysoft.de/fdroid/index/apk/net.primal.android).svg
- [selfprivacy](https://www.f-droid.org/packages/pro.kherel.selfprivacy/).svg
- [simpmusic](https://www.f-droid.org/packages/com.maxrave.simpmusic/).svg
- [spmp](https://apt.izzysoft.de/fdroid/index/apk/com.toasterofbread.spmp).svg
- [tetherfi](https://apt.izzysoft.de/fdroid/index/apk/com.pyamsoft.tetherfi).svg
- [text\_tools\_pro](https://apt.izzysoft.de/fdroid/index/apk/com.dingleinc.texttoolspro).svg
- [wallman](https://apt.izzysoft.de/fdroid/index/apk/com.colorata.wallman).svg
- [waterfly\_iii](https://apt.izzysoft.de/fdroid/index/apk/com.dreautall.waterflyiii).svg
- [wormhole](https://apt.izzysoft.de/fdroid/index/apk/eu.heili.wormhole).svg
- [zipxtract](https://www.f-droid.org/packages/com.wirelessalien.zipxtract/).svg

### CODE REVIEW

**Comment by xprateek** [comment]
:: Some icons broken after compilation
Android Drawables :(
:: Some Fine

**Comment by Kaiserdragon2** [comment]
Your icons need some changes the stroke color should be white and you should always use a stroke to draw a path not an outline with a fill in between.

**Comment by Donnnno** [comment]
Hi, I noticed some things in your icons, please make sure to fix this in your next batch:
- All icons have a square frame around them
image
- Icons are black instead of white
- Sizes are off, circle shapes for example, have many sizes, while they should be 43/44px (like the template files)
- Some shapes are expanded/ have fills, only lines are allowed
image


Already fixed some stuff
image

**Comment by Donnnno** [comment]
Noticed some strange deletions going on your PR so added it in a fresh one. 

Make sure to rebase after every release!

**Comment by xprateek** [comment]
Thanks for fixing my stuff 🫠

**Pull request closed without merging**
