### PR TITLE
icons #358 & #272 & #304 & #306 & #321 + additional font file that is easier to handle

### LINKED ISSUE #272: Icon request
Six icons:
[20210824_072816.zip](https://github.com/Donnnno/Arcticons/files/7041387/20210824_072816.zip)

Feedly, NHS app and WSJ should be straightforward. For 1945, just the number should suffice. Alien Shooter and Galaxy Invaders are more difficult, but I recall someone has done Dust Settle before, which is quite similar, so if possible it would be great.

 Many thanks in advance for your work!

### LINKED ISSUE #304: Icon request
The last ones were great, thank you again (and a small donation went your way!)

One more:

Library

### LINKED ISSUE #306: Icon Request
- [ ] Rave
- [x] Shopee
- [ ] Apk Editor
- [x] Apk Repacker
- [x] App Tester
- [x] Albatross
- [x] AR
- [x] Aurora Store
- [x] Doodle
- [ ] GPSvc
- [ ] Gravador de Voz
- [ ] Transformers - Heavy Metal
- [x] iti Itaú
- [x] C6
- [x] Inmage
- [ ] Kit do SIM
- [x] LewdFI
- [ ] Meu Alelo
- [ ] Minha Oi
- [x] MX Player
- [x] QTranslate
- [x] Clubhouse
- [x] Scrobb
- [x] Songtube
[20210905_123217.zip](https://github.com/Donnnno/Arcticons/files/7110865/20210905_123217.zip)

### LINKED ISSUE #321: Icon Request
[20210903_100922.zip](https://github.com/Donnnno/Arcticons/files/7137350/20210903_100922.zip)

thank you!

### LINKED ISSUE #358: Arcticons Dark Icon Request
*Sent by Hei Wiper (heiwiper@gmail.com). Created by [fire](https://fire.fundersclub.com/).*

---
Manufacturer : motorola  
Model : moto g(6)  
Product : lineage_ali  
Screen Resolution : 1080 x 2160 pixels  
Android Version : 11  
App Version : 2.1.8  
CandyBar Version : 3.12.1  
  
  
MALClient  
com.drutol.malclient/crc64538156a8cca88d64.MainActivity  
<https://play.google.com/store/apps/details?id=com.drutol.malclient>

\--   
Sent from my Android device with K-9 Mail. Please excuse my brevity.

---
*Attachments:*

1. [icon_request_14_09_2021_18_38_12.zip](https://firebot-prod-media.s3.amazonaws.com:443/email-attachments/8ff0e9c2-8348-4fbb-83f7-bf00c2ebed1e/icon_request_14_09_2021_18_38_12.zip)

### PR DESCRIPTION
**Pull request by Quantenzitrone**
closes #358
closes #272
closes #304
closes #306 
closes #321

### CODE REVIEW

**Comment by Aman9das** [comment]
you sure wallstreetjournal is the only app with abbreviation wsj, no harm in longer names, you know..

**Comment by Quantenzitrone** [comment]
idk i just left the names as they were in the zip
i didnt even know wsj ist wallstreetjournal

**Comment by Quantenzitrone** [comment]
weirdly Libary was already in the appfilter but there was no drawable

**Comment by Aman9das** [comment]
Yeah we gotta be careful about shortening names too much, there's 2 apps with the name Turtl on fdroid itself 😕

**Comment by Quantenzitrone** [comment]
> the library icon looks amazing!
I was amazed too when I finished. I didn't actually believe that drawing a Jesus so small only with lines would work so well.

**Comment by Quantenzitrone** [comment]
About the additional font file:
1. all characters consist of only one object (except dots like in i, j or !)
2. all characters are either paths or circles (no lines or polylines)
3. only 2 classes, a for lines and b for dots

**Comment by Donnnno** [comment]
Wow!
A lot of great icons, thanks!!!

**Pull request merged**
