### PR TITLE
Improve BoC icon and amend changelog

### PR DESCRIPTION
**Pull request by aaronhatesregex**

### CODE REVIEW

**Comment by Donnnno** [comment]
Thanks!

**Comment by Donnnno** [comment]
I've checked the icon, a few things for the next time:
- you should take a look at the template folder & [contributing document](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md) again, sizing is wrong I've fixed that now (circles should be 43px)
- line thickness should be 1pt not 0.75pt
- your document should be 48x48px and not pt
- the shapes are asymmetrical and don't connect to each other, this can look quite messy.

image
image

**Comment by aaronhatesregex** [comment]
That's enlightening. To be honest, I just uploaded the old icon and didn't check the updated contributing guideline. Sorry for the inconvenience!

PS: Checked the CONTRIBUTING.md, it's good to know there is a font template.

**Comment by Donnnno** [comment]
Haha okay, it's cool. That's why I check every icon before adding it, I'm quite a perfectionist when it comes to sizing & stuff.

Also, I finally uploaded the font, most icons with text were already using it, but now I'm finally happy with how it looks in general.

**Pull request merged**
