### PR TITLE
30+ new app icons and fixes

### PR DESCRIPTION
**Pull request by skedastically**
Legend:

- **r:** requested icon
- **a:** `appfilter.xml` updated
- **i:** new icon provided
- **o:** alternative icon(s)

___

|App|r|a|i|o|Notes|
|-|-|-|-|-|-|
|**New apps**|
|[AusPost](https://play.google.com/store/apps/details?id=au.com.auspost.android)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/auspost.svg)|||
|[App GHTK](https://play.google.com/store/apps/details?id=com.EComJSC.EComShop)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/app_ghtk.svg)
|`be_alt.svg`|||[x](https://github.com/skedastically/Arcticons/blob/main/other/be_alt.svg)||Legacy logo of be|
|[BeDriver](https://play.google.com/store/apps/details?id=xyz.be.driver)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/bedriver.svg)|||
|[Bee Network](https://play.google.com/store/apps/details?id=network.bee.app)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/bee_network.svg)|||
|[BeExpress](https://play.google.com/store/apps/details?id=vn.dsc.beexpressdriver)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/beexpress_driver.svg)||Using the new logo|
|[BeMerchant](https://play.google.com/store/apps/details?id=xyz.be.merchant)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/bemerchant.svg)|||
|`bidv.svg`|||[x](https://github.com/skedastically/Arcticons/blob/main/other/bidv.svg)||Bank logo|
|[Báo Thanh Niên](https://play.google.com/store/apps/details?id=vcc.mobilenewsreader.thanhniennews)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/bao_thanh_nien.svg)|[1](https://github.com/skedastically/Arcticons/blob/main/other/bao_thanh_nien_alt.svg),[2](https://github.com/skedastically/Arcticons/blob/main/other/bao_thanh_nien_alt_2.svg)|Used a slimmer Arcticon font for main icon and alt 1 (4.2x7.5 or ~5x9). Suggest keeping `bao_thanh_nien_alt.svg` as alt|
|[BIDV SmartBanking](https://play.google.com/store/apps/details?id=com.vnpay.bidv)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/smartbanking.svg)|| Tried to maintain spacing and shape of small flower|
|[CAKE](https://play.google.com/store/apps/details?id=xyz.be.cake)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/cake_bank.svg)|||
|[Chip Defense](https://f-droid.org/en/packages/de.chadenas.cpudefense/)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/chipdefense.svg)|||
|[Edge Screen Note10](https://play.google.com/store/apps/details?id=com.oneUI.vietbm.peopledge)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/edge_screen_note10.svg)|||
|[Fermata](https://play.google.com/store/apps/details?id=me.aap.fermata)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/fermata.svg)|||
|[Gallery365](https://play.google.com/store/apps/details?id=vn.greentea.gallery365.free)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/gallery365.svg)|||
|[INKredible Pro](https://play.google.com/store/apps/details?id=com.viettran.INKrediblePro)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/inkredible_pro.svg)||`inkredible.svg` + pro|
|[Lien Viet 24h](https://play.google.com/store/apps/details?id=vn.com.lpb.lienviet24h)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/lien_viet_24h.svg)|||
|[SafeWA](https://play.google.com/store/apps/details?id=au.gov.wa.health.SafeWA)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/safewa.svg)|||
|[Sendo](https://play.google.com/store/apps/details?id=com.sendo)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/sendo.svg)||Old icon got some problems rendering + appfilter entry missing|
|[TFlat Dictionary](https://play.google.com/store/apps/details?id=com.vn.dic.e.v.ui)|x|x|[x](https://github.com/skedastically/Arcticons/blob/main/other/tflat_dictionary.svg)|||
|[Thanh niên Việt Nam](https://play.google.com/store/apps/details?id=com.vnpt.tnvn)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/thanh_nien.svg)||Initials only should be okay|
|[TNGo](https://play.google.com/store/apps/details?id=com.tngo)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/tngo.svg)|||
|[Trust Wallet](https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/trust_wallet.svg)||Changed appfilter and includes missing icon|
|[TPBank Mobile](https://play.google.com/store/apps/details?id=com.tpb.mb.gprsandroid)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/tpbank_mobile.svg)|
|[TPBank eToken](https://play.google.com/store/apps/details?id=vn.tpb.token.baseotp)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/tpbank_etoken.svg)|
|[Tuổi Trẻ](https://play.google.com/store/apps/details?id=vn.tuoitre.app)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/tuoi_tre.svg)|||
|[Vietnam Airlines](https://play.google.com/store/apps/details?id=com.vietnamairlines.android.app)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/vietnam_airlines.svg)
|[VietNamNet](https://play.google.com/store/apps/details?id=vn.vietnamnet.appvnn)||x|[x](https://github.com/skedastically/Arcticons/blob/main/other/vietnamnet.svg)|||
|**Added mising icons**|
|[Network](https://f-droid.org/en/packages/pl.lebihan.network/) and Network (de.mangelow.network)|||[x](https://github.com/skedastically/Arcticons/blob/main/other/network.svg) ||Includes missing icon (phone symbol + info circle)|
|**Updated appfilter.xml entries**|
|[Camera](https://play.google.com/store/apps/details?id=com.evenwell.camera2) and Camera - com.lenovotab.camera|x|x||||
|Samsung Calendar||x|||Fix `prefix="samsung_calendar_"` to `prefix="calendar_samsung"`|

### CODE REVIEW

**Comment by Donnnno** [comment]
Wow! Amazing work, I'll check them later this week. :-)

**Comment by Donnnno** [comment]
Just checked it, made some small adjustments so we're good to go now!

**Comment by skedastically** [comment]
Yo, after your commit some filenames are mixed up!

Please change:

- beenetwork.svg to beexpress_driver.svg
- beexpress_driver.svg to bemerchant.svg
- bemerchant.svg to bidv.svg
- bidv.svg to beenetwork.svg

Too many bees aha

**Comment by Donnnno** [comment]
oh no! I'll change this when I have time :-)

**Pull request merged**
