### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by K10MR**

### CODE REVIEW

**Comment by K10MR** [comment]
tv.vavoo.app


com.tcc.android.tmw (https://play.google.com/store/apps/details?id=com.tcc.android.tmw) 


com.ionicframework.tv879795 (https://play.google.com/store/apps/details?id=com.ionicframework.tv879795) 


com.vpnufo (https://play.google.com/store/apps/details?id=com.vpnufo) 


com.enel.mobile.xpay (https://play.google.com/store/apps/details?id=com.enel.mobile.xpay

**Comment by Donnnno** [comment]
Hi! Be sure to check the contributors guide before making a pr! Thanks:)

**Comment by K10MR** [comment]
What is a "Pr"?  🤔😅Il 3 ago 2022 01:00, Donno ***@***.***> ha scritto:
Hi! Be sure to check the contributors guide before making a pr! Thanks:)

**Comment by Donnnno** [comment]
Pr: Pull request, this page you created.

and this is the guide: https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md

**Comment by Donnnno** [comment]
Also, please use the Arcticons font here for text icons:
https://github.com/Donnnno/Arcticons/blob/main/templates/arcticons_font.svg

**Comment by K10MR** [comment]
Hi, unfortunately I don't understand English very well. But I understand that I got pretty much everything wrong in making the icons?! 🤔😅
Even the font I got it wrong  😔

**Comment by Donnnno** [comment]
yeah :|

**Comment by K10MR** [comment]
Shit 😅🙈😭

**Pull request closed without merging**
