### PR TITLE
Added some icons

### PR DESCRIPTION
**Pull request by ddavidd**

### CODE REVIEW

**Comment by ddavidd** [comment]
new-icons

**Comment by ddavidd** [comment]
newicons2

**Comment by Donnnno** [comment]
Ready to merge? Or are you still working on this? 

(don't worry about the merge conflict, I'll fix that)

**Comment by ddavidd** [comment]
Ready to merge @Donnnno.

**Comment by Donnnno** [comment]
Very nice icons as I said before, I changed a few things:
- removed a double icon: drops
- resized icons 
- changed 3 icons to make them fit a bit better with the arcticons guidelines:
image


The pixelart is always hard to create with the rounded lines, so it looks a bit werid now.

**Comment by ddavidd** [comment]
Thanks!

**Pull request merged**
