### PR TITLE
Added 9 icons

### PR DESCRIPTION
**Pull request by Th3Third3ye**
Added the following app icons:
Sprouts
MAE
OurGroceries
Geometry Dash Meltdown
Carousell
Insight Timer
Neeva
VES - Image and Photo Compare
Wildberries

### CODE REVIEW

**Comment by Donnnno** [comment]
Still getting merge errors, did you overwrite the whole appfilter file?

**Comment by Th3Third3ye** [comment]
No, i didn't, I just wrote the new lines on top of everything, should I do something different?

**Comment by Donnnno** [comment]
No that should be it, but maybe don't put it at the first line the next time? Just between some other lines should be  fine I guess, this stuff works in mysterious ways 🙃

**Comment by Th3Third3ye** [comment]
Okay!! I hope the next time it works without problem lol

**Comment by kaanelloed** [comment]
Your text editor modifies the file's end-of-line sequence, which should remain LF, but in the pull request it's CRLF.

**Comment by Th3Third3ye** [comment]
Ohhh!! Okayy, I will change that then, thx

**Comment by Donnnno** [comment]
Merged it in another request, I suggest installing VS Code :)

**Pull request closed without merging**
