### PR TITLE
Stroke auto 1 or 0

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
If stroke with is near 1 or 0 it will be automatically applied to 1 or zero instead of printing it to the console

### CODE REVIEW

**Comment by Donnnno** [comment]
Does this have any impact on SVG's without the stroke_width property (because the default amount is 1)

**Comment by wwwwwwari** [comment]
While we're at it, can we have an auto color rounding to `#ffffff` as well? InkScape loves to mess with the color 😂

**Comment by Kaiserdragon2** [comment]
if there is no stroke defined (so it is the default 1) nothing changes only something like 0.999 will get 1

**Comment by Kaiserdragon2** [comment]
> While we're at it, can we have an auto color rounding to `#ffffff` as well (e.g. from `#fafafa` `#fbfbfb` and so on)? InkScape loves to mess with the color 😂

at the moment the script checks it, but it needs to be manually edited and i don't know if every case is catched with this because there are many methods to define a color and to automatically change something that's near white to white for every of this cases isn't easy to do without fucking up in some cases

**Pull request merged**
