### PR TITLE
icons

### PR DESCRIPTION
**Pull request by Zullinsky**
Bit, Clalit online, crossword (hebrew), Me - caller ID, Rav - Kav Online, Pepper - online banking.

These are some app icons I had missing on my phone.

### CODE REVIEW

**Comment by Zullinsky** [comment]
I had changed the files like the instructions, 
I also gathered the code with the app.
do I need to Pull Request it separately?

**Comment by Donnnno** [comment]
Great! 
You can add it to this commit, in that way I can check everything more easily.

**Comment by Zullinsky** [comment]
done

**Comment by Donnnno** [comment]
Took a deep dive into the Hebrew alphabet for this one 😅 

Not a fan of outline letters in general, so that was a good opportunity to expand the font (still working on it), so if you have feedback, please let me know.

image


image

**Comment by Donnnno** [comment]
Oh, and please make sure that the names in the appfilter are the same as the icon names.

**Comment by Zullinsky** [comment]
Woah, that is very impressive.
As far as I can tell the font looks good. 
Should I change the icon files names?

**Comment by Donnnno** [comment]
Thank you! No need to do anything from your side, I've merged your icons already. :-)

**Comment by Zullinsky** [comment]
Alright, thank you for the help and the work on the icons.
I wish you well.

**Pull request merged**
