### PR TITLE
Added icons

### LINKED ISSUE #439: Arcticons Dark Icon Request
BirdNET
de.tu_chemnitz.mi.kahst.birdnet/de.tu_chemnitz.mi.kahst.birdnet.Activity_SplashScreen
https://play.google.com/store/apps/details?id=de.tu_chemnitz.mi.kahst.birdnet

Combi.de
de.combi/de.mytime.activity.MainActivity
https://play.google.com/store/apps/details?id=de.combi

SmartThings
com.samsung.android.oneconnect/com.samsung.android.oneconnect.ui.SCMainActivity
https://play.google.com/store/apps/details?id=com.samsung.android.oneconnect

SMS Backup+
com.zegoggles.smssync/com.zegoggles.smssync.activity.MainActivity
https://f-droid.org/en/packages/com.zegoggles.smssync/

Teilen nach
net.gsantner.markor/net.gsantner.markor.activity.openeditor.OpenShareIntoActivity
https://f-droid.org/en/packages/net.gsantner.markor/

To-Do
net.gsantner.markor/net.gsantner.markor.activity.openeditor.OpenEditorTodoActivity
https://f-droid.org/en/packages/net.gsantner.markor/

---
*Attachments:*

1. [icon_request_25_09_2021_14_02_32.zip](https://firebot-prod-media.s3.amazonaws.com:443/email-attachments/ee8d5958-a88c-42ce-b4b2-f5bf58c3349c/icon_request_25_09_2021_14_02_32.zip)
1. [signature.asc](https://firebot-prod-media.s3.amazonaws.com:443/email-attachments/ee8d5958-a88c-42ce-b4b2-f5bf58c3349c/signature.asc)

### PR DESCRIPTION
**Pull request by ddavidd**
- BirdNET
  - Combi.de
  - SmartThings
  - SMS Backup+
  - Teilen nach
  - To-Do
newicons

### CODE REVIEW

**Comment by Donnnno** [comment]
Those are great!

**Comment by ddavidd** [comment]
newicons
newicons

**Comment by Donnnno** [comment]
the postcard one already has an icon! 
But the others look great again

**Comment by ddavidd** [comment]
Oh, oops! I didn't see the postcard icon. And thanks! 😄

**Comment by Donnnno** [comment]
image

Somethings not right here :S

**Comment by ddavidd** [comment]
Oops. Gimme a minute.

**Comment by ddavidd** [comment]
Bah! Hold on...

**Comment by Donnnno** [comment]
Thanks for the quick fix! About to create a new release :^)

**Comment by ddavidd** [comment]
Okay. Should be good to go.

**Comment by Donnnno** [comment]
Cool!

**Pull request merged**
