### PR TITLE
Use circular arcs in AudioFX icon

### PR DESCRIPTION
**Pull request by GrantMoyer**
The curves in the AudioFX icon were noticably non-circular. This change uses true circular arcs in the icon.

Rendered (old curve in red for comparison):

audiofx

### CODE REVIEW

**Comment by Donnnno** [comment]
Loving the eye for detail here! That's very rare haha

**Comment by Donnnno** [comment]
You can put all your icons in one pull request the next time btw :)

**Comment by GrantMoyer** [comment]
> You can put all your icons in one pull request the next time btw :)

Noted

**Comment by Donnnno** [comment]
Hi, I've manually merged your commits because of some merge errors, but thanks for your work!

**Pull request closed without merging**
