### PR TITLE
Added 8 icons

### PR DESCRIPTION
**Pull request by xenicx**
Icons added:
- [Brace](https://play.google.com/store/apps/details?id=com.bracedotto)
- [Buckwheat](https://apt.izzysoft.de/fdroid/index/apk/com.danilkinkin.buckwheat)
- [Frosty](https://github.com/tommyxchow/frosty)
- [Govee Home](https://play.google.com/store/apps/details?id=com.govee.home)
- [History Of Me](https://android.izzysoft.de/repo/apk/com.litlifesoftware.historyofme)
- [Kide.app](https://play.google.com/store/apps/details?id=com.treanglo.bailataan)
- [One second diary](https://github.com/KyleKun/one_second_diary)
- [Tuudo](https://play.google.com/store/apps/details?id=fi.caleidon.tuudo)

### CODE REVIEW

**Comment by Donnnno** [comment]
Lots of stuff happening here.
Why remove a name from the contributors list and why so many appfilter entry removals?

**Comment by xenicx** [comment]
I added it there [myself](https://github.com/Donnnno/Arcticons/pull/1225/commits/fdeb0c9cb116515bf1e315631f853cc1151fff9c) so I have right to remove it also? And I forgot to update to the latest appfilter.xml :sweat_smile:

**Comment by Donnnno** [comment]
Oh sorry, was confused by the username / contributor name combo, and it's also pretty unusual to remove yourself as a contributor. 🙃 

Can you still update your appfilter? Can't merge it otherwise :-)

**Comment by xenicx** [comment]
I assume it is good now?

**Comment by Donnnno** [comment]
Ehh, it's easier to just rebase and apply your changes again. Can't accept an appfilter file with 18k changes.

**Pull request closed without merging**
