### PR TITLE
2 icons + regional

### PR DESCRIPTION
**Pull request by Redbox3070**
added 2 icons and updated appfilter to match some icons to regional variants

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi! Thanks for the icons, some feedback:

the icons right now have some double lines, I think it could be more minimal, like this (first icon):

image


Also, something's going wrong with the appfilter, you might wanna redo that and add the lines of code with a text editor like VS Code

**Comment by Donnnno** [comment]
Nice work!

**Comment by Redbox3070** [comment]
> Nice work!
thanks. sorry if i doo too many commits but i'm not familiar with github. 
trenord icon was already available but it was not showing so i updated the appfilter, payback.svg icon was already available in a variant so mine is not necessary

**Comment by Donnnno** [comment]
I understand! It looks good now :-) 
Thanks for the fixes

**Comment by Donnnno** [comment]
Going through your icons and noticing that Genius scan already has an icon 

image

**Pull request merged**
