### PR TITLE
Added Icons (Crayon, Cryten, Mohafiz, Simplicon, My Nayatel & JazzCash)

### PR DESCRIPTION
**Pull request by hassanncreative**
```
<!-- Crayon -->
<item component="ComponentInfo{com.jndapp.cartoon.crayon.iconpack/com.jndapp.cartoon.crayon.iconpack.MainActivity}" drawable="crayon"/>
```

```
<!-- Cryten -->
<item component="ComponentInfo{com.vertumus.cryten/com.vertumus.cryten.activities.SplashActivity}" drawable="cryten"/>
```

```
<!-- Mohafiz -->
<item component="ComponentInfo{com.humanetek.apps.muhafiz/com.humanetek.apps.muhafiz.activities.WelComeScreenWork.SplashActivity}" drawable="mohafiz"/>
```

```
<!-- Simplicon -->
<item component="ComponentInfo{com.jndapp.iconpack.simplicon/com.jndapp.iconpack.simplicon.MainActivity}" drawable="simplicon"/>
```

```
<!-- MyNayatel -->
<item component="ComponentInfo{com.mynayatel/com.mynayatel.SplashScreen}" drawable="mynayatel"/>
```

### CODE REVIEW

**Comment by hassanncreative** [comment]
Articons_26_1_22

**Comment by hassanncreative** [comment]
Did few minor modifications in some icons too. I have uploaded them in  `/other` folder as you said.

**Comment by Donnnno** [comment]
Why change those two other icons? They don't have correct sizing now and are out of balance.

**Comment by hassanncreative** [comment]
> Why change those two other icons? They don't have correct sizing now and are out of balance.

Sorry which two?

**Comment by Donnnno** [comment]
Nayapay and universalcopy

**Comment by hassanncreative** [comment]
Well, I don't see any sizing problem with it as I didn't change any major thing. Just changed corner radius a a bit and in NayaPay just changed its icon position inside the circle. Didn't touch the overall size of the icons.

**Comment by Donnnno** [comment]
You should probably fetch up with the upstream for that:
image

**Comment by hassanncreative** [comment]
> You should probably fetch up with the upstream for that: image

man I don't know about this technical stuff that is why I asked beforehand how to modify icons. You told me to put those in /other folder which I did but I think I messed up something. =(

**Comment by Donnnno** [comment]
Oh no worries! I'll explain. 

After each update, the main branch (Donnnno:main) gets updated. But your own fork (hassanncreative:main) doesn't get automatically updated with that. So you have to fetch the upstream to update it: 
image

You can do that there ^

**Comment by hassanncreative** [comment]
I did fetch upstream and it opened a pull request in my repo but it says "This branch has conflicts that must be resolved to resolve conflicts before continuing" in the end.

**Comment by Donnnno** [comment]
I think you can fix that by deleting the new ones? But I have no idea, anyways it means I can't merge it too :s

**Comment by Donnnno** [comment]
Oh that fixes the issue, and can you fetch the upstream now?

**Comment by hassanncreative** [comment]
I deleted those two and yes the conflicts are resolved for now.

**Comment by Donnnno** [comment]
And after that, you should be able to add the files again :)

**Comment by hassanncreative** [comment]
Yes I just did fetch and merge. Should I add those two files again? Because I want to modify those.

**Comment by Donnnno** [comment]
Yes!

**Comment by hassanncreative** [comment]
Okay will do right now I am away from my computer. Thanks.

**Comment by hassanncreative** [comment]
I installed Lawnchair launcher today and noticed that it doesn't automatically detect some of the icons which I made in the past. It happens with Nova launcher too but from there I can customize and select an icon manually from the list but lawnchair doesn't have an option to do that.

So I think there is something wrong with the code or something.

**Comment by Donnnno** [comment]
Can you send the appfilter data again? 

Btw you can add it yourself pretty easily too, just add the lines to the appfilter.xml document here: https://github.com/Donnnno/Arcticons/blob/main/other/appfilter.xml

And don't worry about where you place it, it gets sorted automatically after every release ;)

**Comment by hassanncreative** [comment]
> Can you send the appfilter data again?
> 
> Btw you can add it yourself pretty easily too, just add the lines to the appfilter.xml document here: https://github.com/Donnnno/Arcticons/blob/main/other/appfilter.xml
> 
> And don't worry about where you place it, it gets sorted automatically after every release ;)

Yes, I just did add appfilter for 9 icons and created pull request. The data was missing

**Comment by hassanncreative** [comment]
jazzcash

```
<!-- JazzCash -->
<item component="ComponentInfo{com.techlogix.mobilinkcustomer/com.ibm.jazzcashconsumer.view.splash.SplashActivity}" drawable="jazzcash"/>
```

**Pull request merged**
