### PR TITLE
Add Artemis

### PR DESCRIPTION
**Pull request by lividhen**
- Add Artemis sgv
- Add Artemis to appfilter
- Fix line ending for Forkyz

### CODE REVIEW

**Comment by lividhen** [comment]
Aparently adding a line to app manifest has counted as rewriting the whole file

**Comment by wwwwwwari** [comment]
> Aparently adding a line to app manifest has counted as rewriting the whole file

I haven't checked your files but you might want to make sure that your text editor didn't change the line feed character from `LF` to `CRLF`.

**Comment by lividhen** [comment]
Yep that's what happened 😆. Thanks

**Comment by Donnnno** [comment]
Nice work!

**Pull request merged**
