### PR TITLE
redesign about, date-widget

### PR DESCRIPTION
**Pull request by Aman9das**
Now also adding candybar manually, so that customising is possible :)

### CODE REVIEW

**Comment by joelchrono12** [comment]
I would make the profile pics circles instead of squares but idk

**Comment by Aman9das** [comment]
Yeah, I meant it as a prototype.. you guys must improve the graphics coz i'm no artist :)

**Review by Donnnno — CHANGES_REQUESTED** [review]
Can you undo the appfilter blabber.im changes?

**Comment by Aman9das** [comment]
But the drawable is blabber.svg..

blabber.im isn't working, so i looked for the problem, and found the problem..

Alternatively I can rename the svgs to blabberim.. i guess that is what you want to be done

Anyway don't merge before the f-droid release is out, i don't know what the problem was with java but hopefully simple to fix

**Comment by Donnnno** [comment]
Yea, not planning to merge anything before that's fixed.

**Comment by Aman9das** [comment]
hey tell what you want drawable=blabber or blabberim.svg 

ANYWAY FINALLY REMOVED CANDYBAR LIBRARY DEPENDENCY. Now we have our own working copy, you can see the jdk-1.8 was also in there for backwards compatibility, and we can add the f-droid link logic and everything

This is amazing!

**Comment by Donnnno** [comment]
Damn this is great work

**Comment by Donnnno** [comment]
Do we need all these library items to be in here tho? 
image

**Comment by Aman9das** [comment]
Thanks,
And yeah, we have a lot of pruning/customization to do..

We need help to figure out what is requesting each permission etc..

But let's wait for the f-droid build to publish first..
@Donnnno you should work on the email issue in the meanwhile..

Just set up arcticons@onnno.nl to forward to fire-bot email-id somehow. That is very important.

**Comment by Aman9das** [comment]
Turns out the libs/app folder was completely unnecessary🙃

Hopefully tomorrow fdroid build publishes properly!

**Comment by Donnnno** [comment]
Gonna take a look at this huge PR today :^)

**Comment by Donnnno** [comment]
Hi, everything looks good!
I just changed a few things:
- new image for the date widget previews
- fixed the blabber entry in the appfilter
- resized the new icons

Can you please use the template files the next time you're creating icons, your icons are far too big? I'm getting documents from you that are 1080px while the icons itself should be 48px.

**Pull request merged**
