### PR TITLE
Update appfilter.xml

### PR DESCRIPTION
**Pull request by PixelRuzt**
Two new icons added

### CODE REVIEW

**Comment by wwwwwwari** [comment]
Hey @PixelRuzt! I'm not an actual reviewer/maintainer of this project but I think you'll probably need to adjust your changes a bit:

1. In `appfilter.xml`, we don't put `<appfilter>` and `</appfilter>` around the new entries. Generally, we just add only 2 lines (excluding blank lines) for each new icon we add to the `appfilter.xml` like this:
```
  <!-- my app name -->
  <item component=blah blah...  />
```
2. Your text editor changed `appfilter.xml`'s line break characters to CRLF but it needs to be just LF. If you're on Windows, [Notepad++](https://stackoverflow.com/a/8195860) can be used convert CRLF to LF.
3. I don't see any of your pull requests containing the actual icons (the .svg files). Did you perhaps forget to submit them?
4. If this is your first time contributing, you might want to add yourself to `app/src/main/res/xml/contributors.xml` as well :)

**Comment by PixelRuzt** [comment]
Hey @wwwwwwari ,
Thank you so much for reaching out to me and explaining all of this stuff. 

I'm sorry about all this mess, I'm new to GitHub and I am struggling a bit to get a grasp of how things are and how they work. Just learning as I go about it.

I would appreciate if you could guide me to some tutorials or a channel that teaches all the basic stuff for GitHub.

1. I'll correct my entry to `appfilter.xml` according to your suggestions. I also need to ask, if I'm working on a icon and want to add it to this. How should I attain it's package name? Do I need to install them on my phone first? No other way?

2. I think I messed that up by using `Notepad`. I'll use `Notepad++` or something next time.

3. I just checked and I made the pull request to some other thread or repository I think. It is there but connected to some other. I'll redo that after I've sorted put together all the requirements properly.

4. Thank you, I'll add myself to the list after I've made a proper contribution and not a mess.

Please feel free to correct me anywhere I make mistakes.

Thank you.

**Comment by wwwwwwari** [comment]
@PixelRuzt I'm a new contributor like you so no worries! Git can be very confusing when you're new. For your points:

1. The only way I know is to install the app first and use the [IconRequest](https://github.com/Kaiserdragon2/IconRequest/releases) app per the [contributing guide](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md), yes. But again, I'm also a new contributor myself so there might be another way I don't know about.
2. Yes, Windows Notepad always convert any `LF` in the file to `CRLF`, and it also has problems reading files that use just `LF` instead of `CRLF` if I'm remembering correctly. I think if you already have VS Code you can use that to update the files too. Just avoid Notepad 😅
3. Yeah, I saw your repository and basically you're making a separate branch for each change (one for requests, one for appfilter, one for icons). For the sake of simplicity, you actually only need to make all the changes in one branch then submit those changes in one pull request. 

I don't really know any guides than just googling around, but [this](https://github.com/firstcontributions/first-contributions) might work.

**Comment by PixelRuzt** [comment]
@wwwwwwari I am sorry for troubling you again. I have made some changes to my pull requests. Please go through it and my feed to see if I have made it in the correct place. 
Thank you in advance.

**Pull request closed without merging**
