### PR TITLE
9 new icons: lyfpay, kvsitso, posteid, iprint_and_scan, dankchat, limbo_x86, notification_dictionary, kubenav, sicmu_player

### PR DESCRIPTION
**Pull request by fanfu**
plus added creditcoop again in the xml file

### CODE REVIEW

**Comment by Donnnno** [comment]
this one has some issues!

Double icons:
- iprintandscan
- postid

Broken svg:
- sicmu_player

appfilter issues
- 
    
    <item component="ComponentInfo{io.kubenav.kubenav

**Comment by Donnnno** [comment]
Hi! Can you export sicmu_player again? I can't seem to open it. Also, you should take a look at the kubenav entry in appfilter.xml before merging.

**Comment by fanfu** [comment]
Hi @Donnnno! Sorry for the mess and the long delay. Something new happened in my life a few weeks ago 👶 and I have not yet managed to find a new pace.
I think it should be ok this time…

**Comment by Donnnno** [comment]
@fanfu Congrats!!, that's big news!

I'll take another look at the pr :)

**Pull request merged**
