### PR TITLE
20 New Icons Added

### PR DESCRIPTION
**Pull request by npnpatidar**
file names changed as asked

### CODE REVIEW

**Comment by Donnnno** [comment]
I forgot, you also need to add all the corresponding appfilter entries, you can gather them with [Icon Request](https://github.com/Kaiserdragon2/IconRequest/releases), and add them to the [appfilter file](https://github.com/Donnnno/Arcticons/blob/main/other/appfilter.xml), but make sure all `drawable` names are the same as your icon names

**Comment by Donnnno** [comment]
Hi @npnpatidar! Do you have some time in the coming days for this?

**Comment by npnpatidar** [comment]
Can I append new entries in appfilter file or do i have to add entries in between according to their alphabetical order

**Comment by npnpatidar** [comment]
Also in some icons which I have added, there is something wrong with brightness. Is there any fix stroke width which you are adhering to ? For example please check indian express icon.

**Comment by Donnnno** [comment]
You can put them at the end or the beginning, it doesn't matter actually because it gets sorted with every release.

**Comment by Donnnno** [comment]
> Also in some icons which I have added, there is something wrong with brightness. Is there any fix stroke width which you are adhering to ? For example please check indian express icon. 

I'll take a look!

**Comment by Donnnno** [comment]
Heyo, you didn't need to close the issue! 

If you have trouble with the appfilter, you can also paste the lines of code right here :)

**Comment by npnpatidar** [comment]
I am new to github. I need to make changes in some icons also so i thought  i will do all the changes and then do another pull request.

**Comment by Donnnno** [comment]
Ah that's fine! Just let me know if you need some help :)

**Comment by npnpatidar** [comment]
Ok thanks. I do have one question. I made some icons for webapps. How can I add that since I won't have appfilter entries for them.

**Pull request closed without merging**
