### PR TITLE
Uploading a few more icons that I made

### PR DESCRIPTION
**Pull request by PixelRuzt**
This pull request is here so it adds three icons for:

- JustWatch
- NoteIt
- Pixel Search

I am not sure if I'm using the branch thing correctly since I just made the edits to the 'main' as far as I can understand. I did create a branch specifically for this upload but it somehow didn't get used.

### CODE REVIEW

**Comment by wwwwwwari** [comment]
That's 20k lines added and 20k lines removed again. 😅

**Comment by PixelRuzt** [comment]
OMG did I really do that? 😶‍🌫️
I'm not sure how so many changes were made. I only made a few necessary changes. I have no idea how it blew up to this much.

**Comment by PixelRuzt** [comment]
I think I've figured out what happened. The `appfilter.xml` got changed to crlf from lf again since I used the web editor for it. Can you confirm if that is the case here?

**Comment by wwwwwwari** [comment]
Just fix it like last time should be OK :D

**Comment by PixelRuzt** [comment]
Yea, I think. I'll have to look into the desktop version this is getting quite out of hand.

**Comment by PixelRuzt** [comment]
@wwwwwwari do I have to wait for one set of commits to be merged before I can make another branch for a new upload?

**Comment by Donnnno** [comment]
Looks good now!
You can still add new icons & stuff to this branch :-)

**Comment by PixelRuzt** [comment]
Hi @Donnnno,
I have added three more icons to this branch and now it's complete and ready to be merged.
Let me know if there's something missing or wrong.

I had made a few icons but when I wanted to remove them from `requests.txt` they were already gone. How does this process go about? Will you be comparing the submissions for the best one or will it be _first come first serve_ policy?

Thank you.

**Comment by Donnnno** [comment]
Great looking icons!

**Pull request merged**
