### PR TITLE
Two new icons. First time submit. Hi there :)

### PR DESCRIPTION
**Pull request by PixelRuzt**
Hi, 
This is my first time here on GitHub and promptly my first time contributing something.
 It has been quite a learning curve to understand the platform and everything.
 But with some help from fellow contributors and some googling stuff.
 I have corrected some flaws in my original pull requests.
 
 Feel free to point out any flaws in this one.
 
 Thank you.

### CODE REVIEW

**Comment by PixelRuzt** [comment]
I changed my requests file because it was not the correct LF format.

**Comment by wwwwwwari** [comment]
Note: I made a quick review, but again, **I am not the actual reviewer/maintainer**. Donnnno might come in later and suggest more changes to your files :>

Your `appfilter.xml` still needs adjustments.

1. The file with `CRLF` problem is **not** `requests.txt`, but `appfilter.xml`, which still use `CRLF` instead of `LF`. 
2. Your icon name for KTM India is not what what its entry in `appfilter.xml` says the name should be. If you look at your newly added entry for KTM India in `appfilter.xml` (beginning with `<item component=`...), you'll see that it has `drawable="ktm_india"`, and so your KTM India icon needs to be named `ktm_india.svg`, not `ktb copy.svg` or anything else.
3. This is just a general formatting issue, but the entire `appfilter.xml` begins with 2 space characters, but your new lines begins with a tab. I'm not sure how much this would affect the whole thing but for the sake of consistency I'd make the new lines match everything else (2 spaces instead of a tab)

Quick tips to self-check for the issues with your pull request - remember that your request are for only a couple of icons, but if you look at the top of this pull request, it says there's 21312 lines added and 21259 lines removed! 
image

For a comparison, my pull request to add 23 icons in #1596 only involves 168 new lines and 142 removed lines.

If you don't remember making such a big change, it means something's still wrong with your file (mostly the line break issues). :)

**Comment by PixelRuzt** [comment]
okay,
 thank you very much. this is very helpful.
 
 1. I only edited the `appfilter.xml` on the website's own editor. Like the option on the top right of it when you're viewing the code. How do you think I should avoid that? Do I have to download-edit-delete-reupload it as I did for the `requests.txt` ? or is there a better way?
 2. Oh alright got it. That makes sense. I will definitely correct it right away.
 3. Ok. Yea, I remember putting a tab there because I was unsure how to make it match the rest of the format. I'll fix that as well.
 
 Once again, really appreciate you taking time out to correct me and reviewing my submits. I'm definitely learning a lot.

**Comment by wwwwwwari** [comment]
> I only edited the `appfilter.xml` on the website's own editor. Like the option on the top right of it when you're viewing the code. How do you think I should avoid that? Do I have to download-edit-delete-reupload it as I did for the `requests.txt` ? or is there a better way?

My workflow is technically download-edit-upload, yes. Specifically, I use `git` command line to copy the the entire repo into my pc, edit the files locally, then upload to my repo and open a pull request. It takes some time to learn but it's the standard process for contributing to many FOSS projects.

If you want to keep it simple without `git`, you can also download the raw file, edit it with, say, Notepad++, then upload to replace the old files to your repo and make a pull request, that'd work too. I've never used the web editor interface so you'll probably need to figure it out or consult Google if that's what you want to use.

**Comment by PixelRuzt** [comment]
alright, I think that should do the trick. I'll try doing that.
I just don't wanna use Desktop app or something and just keep it light. Thus I prefer the website.

**Comment by PixelRuzt** [comment]
@wwwwwwari Hi, Sorry for troubling you again. I have done all the necessary things from my end (I believe). How will I know if my icons have been accepted or not. 
Or have I missed a final crucial step like submitting the pull request for the process to be completed?
Or have they already been accepted?

**Comment by Donnnno** [comment]
Hey! Thanks for your icons @PixelRuzt I know that getting to know git can be quite hard, thanks a lot @wwwwwwari for helping with that :) I was a bit busy last week.

**Comment by Donnnno** [comment]
Just checked your icons, they look good, so merging them now :)

**Comment by Donnnno** [comment]
Correction, your branch is protected, so I can't merge. You can change that here:

image

**Comment by PixelRuzt** [comment]
Thank you so much 😊.

Oh my bad! 🥺 GitHub was constantly telling me to protect it or something. So I did it. I'll change that.

**Comment by Donnnno** [comment]
haha no worries, protecting the main branch is a good thing to do! 

But if you make changes in that main branch, I can't make changes :)

**Comment by PixelRuzt** [comment]
Yea, I've started to make some efforts to learn more about GitHub.

I'll learn how to do that protection thing without disrupting the merging thing.

**Pull request merged**
