### PR TITLE
9 +11 new Icons by PixelRuzt

### PR DESCRIPTION
**Pull request by PixelRuzt**
Hello,
I have fulfilled a few icon requests by hand-picking a few top-requested ones. Do let me know your feedback on these and if you like them.

Here's a list of icons uploaded in this pull request:

- lenskart
- artifact
- beeper
- dream
- mobile manager
- pathao
- samsung cloud
- showly oss
- that shopping list

Warm regards.

### CODE REVIEW

**Review by PixelRuzt — COMMENTED** [review]
Removed the 9 icon requests for the current pull request and 1 for a already fulfilled request.

**Comment by PixelRuzt** [comment]
Hello again,

I enjoyed creating the previous ones so much that I ended up making a few more icons. It was quite a fun and lightly challenging task that I had fun dealing with.
Hope you'll like the icons.

Here's a list of icons in the second upload:

- aakash tutor
- free basics
- freshwalls
- hoichoi
- hotmart
- icc
- mortal kombat
- reminder pro
- star walk 2
- typewise
- zara

Regards.

**Comment by Donnnno** [comment]
Great looking icons! I've cleaned some of the shapes a bit up, and resized them

**Comment by PixelRuzt** [comment]
> Great looking icons! I've cleaned some of the shapes a bit up, and resized them

@Donnnno Thank you so much 🙏.

Could you help me understand what kind of cleaning up was required.
It would be really helpful to learn and perfect my next submission.
Also, how do you resize them? Do you mean the scale of the icons or the file size or something?

**Comment by PixelRuzt** [comment]
Aah alright! I see it now.
I'll make it a point to go through them on my on and try to keep them clean and proportional to the templates.
Thank you.

Did any of the icons not make the cut? I saw 'Reminder Pro' icon request was re-added by you.

**Comment by Donnnno** [comment]
yeah the requests.txt works quite mysterious. I was getting a merge error, so I added it to the list again, and then I could merge it, idk why it caused an issue tho.

**Pull request merged**
