### PR TITLE
Added 2 new icons

### PR DESCRIPTION
**Pull request by ThomasTraineau**
com.simplemobiletools.calendar.pro (calendar) and com.maxmpz.audioplayer (poweramp)

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, Thanks for your submissions! 

Simple calendar pro has already an icon, can you use Turtl and collect the data? Then I can check where the problem lies. Right now, it uses a dynamic calendar icon, I can use your one as static one because I like your design ;) 

Your Poweramp icon looks just like the existing media player one so I think it's better to use that one.

Can you collect the full data needed with the turtl app? Thanks!

**Comment by ThomasTraineau** [comment]
Hi, here is the collected data from turtl : 


<item component="ComponentInfo{com.simplemobiletools.calendar.pro/com.simplemobiletools.calendar.pro.activities.SplashActivity.Grey_black}" drawable="calendar"/>


Although for poweramp, the double circle is nice and different from the mediaplayer. Would be nice to see it in the pack :)

**Comment by Donnnno** [comment]
> the double circle is nice and different from the mediaplayer

True but the distance between the two needs to be bigger, otherwise it will look distracting for your eyes because two shapes are too close to each other.

**Comment by ThomasTraineau** [comment]
O sorry the data didn't get pasted :


<item component="ComponentInfo{com.simplemobiletools.calendar.pro/com.simplemobiletools.calendar.pro.activities.SplashActivity.Grey_black}" drawable="calendar"/>

**Comment by ThomasTraineau** [comment]
here is the modified logo : https://anonfiles.com/1aO67dyeu1/poweramp_svg

**Comment by Donnnno** [comment]
Can you also paste the poweramp data here?

**Comment by ThomasTraineau** [comment]
Here it is :

`
<item component="ComponentInfo{com.maxmpz.audioplayer/com.maxmpz.audioplayer.standard_adaptive}" drawable="poweramp"/>
`

**Comment by Donnnno** [comment]
Just released 1.6.4, but I forgot to apply the new simple calendar icon, so you will probably see the old one. But it's fixed for the next release :)

**Comment by ThomasTraineau** [comment]
Nice, I also don't see the poweramp logo but I'll be waiting for the next release then !

**Comment by Donnnno** [comment]
What version are you using? I just released 1.6.4 like an hour ago.
The F-Droid release is currently one version behind.

**Comment by ThomasTraineau** [comment]
Yes indeed I'm on 1.6.3 from f-droid

**Comment by Donnnno** [comment]
Then you have to wait a bit for F-Droid to update

**Pull request merged**
