### PR TITLE
Added 10 new icons

### PR DESCRIPTION
**Pull request by phampyk**
It's my first time so I hope I did everything okay. Some icons are PWA so basically shortcuts to webs, but I hope they are okay.
Please let me know if I should change anything.

### CODE REVIEW

**Comment by Aman9das** [comment]
How to install those PWAs

**Comment by phampyk** [comment]
@Aman9das When you open the website it shows a pop-up saying "install on device" and it shows in your phone like another app.

**Comment by Donnnno** [comment]
Hey thanks for your contribution! Creating icons for PWAs is totally fine! But I normally don't make them because of their unique IDs, feel free to add more tho :)

**Comment by Donnnno** [comment]
The icons are great btw! Just made some small adjustments (mostly resizing)

**Pull request merged**
