### PR TITLE
Add 60+ icons and a few other changes

### LINKED ISSUE #1602: Icon for Seven Time not showing
The icon for Seven Time no longer shows for me. I think it uses a generic number-in-a-square icon, maybe something just needs to be changed in appfilter.xml?

`<!-- Seven Time -->`
`<item component="ComponentInfo{com.codescape.seventime/com.codescape.seventime.MainActivity}" drawable="number_square_7"/>`

Using Nova Launcher 7.0.57 with Arcticons Dark 6.4.4.
Thank you for your work on this gorgeous icon pack!

### PR DESCRIPTION
**Pull request by wwwwwwari**
This PR includes the following changes:

1. Fix #1602 and other icons having similar issues (4PDA, 9UHDMAX V5, Protect, Seven, Sieben, and ULTRAFLOW 2) - not sure if you're already working on this; if you are, feel free to drop (bypass? skip? I don't know the terms) this commit: 7da743e44c6bceb1b40741ed93ae13ae640506c8.
2. Add new variant of TwitCasting
3. Add new alternative icon for Blue Archive
4. Add icons for 62 new apps (Connect for Lemmy and CH8 reuse existing icons), and modify appfilter.xml and requests.txt accordingly.

Let me know if there's anything I should adjust.

### CODE REVIEW

**Comment by Donnnno** [comment]
wowwwwww

**Comment by Donnnno** [comment]
Just looked at the number thingy, looks like I forgot to rename the square number icons, probably should do that for consistency

**Comment by wwwwwwari** [comment]
Just wondering but do we have some sort of scripts that check for appfilter entries that point at icons that don't exist? I'm thinking that if we had one and ran it periodically (maybe automatically during the build?), it would catch this kind of issue pretty easily.

**Comment by Kaiserdragon2** [comment]
> Just wondering but do we have some sort of scripts that check for appfilter entries that point at icons that don't exist? I'm thinking that if we had one and ran it periodically (maybe automatically during the build?), it would catch this kind of issue pretty easily.

The IconRequest App can do that but it isn't implemented in any script yet.

**Comment by Donnnno** [comment]
Hoping to merge it this weekend, but it's a large one to check haha

**Comment by wwwwwwari** [comment]
Hey, there's no rush, I know it's a big one. 😅 Maybe I should've split it into a few parts after all.

**Comment by Donnnno** [comment]
halfway there

**Comment by kaanelloed** [comment]
> > Just wondering but do we have some sort of scripts that check for appfilter entries that point at icons that don't exist? I'm thinking that if we had one and ran it periodically (maybe automatically during the build?), it would catch this kind of issue pretty easily.
> 
> The IconRequest App can do that but it isn't implemented in any script yet.

Isn't the purpose of the check_drawable script ?

**Comment by Kaiserdragon2** [comment]
> > > Just wondering but do we have some sort of scripts that check for appfilter entries that point at icons that don't exist? I'm thinking that if we had one and ran it periodically (maybe automatically during the build?), it would catch this kind of issue pretty easily.
> > 
> > The IconRequest App can do that but it isn't implemented in any script yet.
> 
> Isn't the purpose of the check_drawable script ?

You are right totally forgotten about that one, even though I have written it. It should probably be implemented into the release workflow (called from the preparerealese script).

**Comment by Donnnno** [comment]
Checked all of them! Amazing looking icons, thanks a lot!

**Pull request merged**
