### PR TITLE
5 new icons. 1 tool and 4 games =]

### PR DESCRIPTION
**Pull request by hacknorris-aka-penguin**
so yes. list of apps included in other folder : 
- [zip me](https://play.google.com/store/apps/details?id=zip.me)
- games:
- - [enigmbox](https://play.google.com/store/apps/details?id=com.benoitfreslon.thinkoutsidethebox)
- - color games (https://play.google.com/store/apps/dev?id=6731838628059519714 cause he made some very similar differencing only colors)
- - [little alchemy](https://play.google.com/store/apps/details?id=com.recloak.littlealchemy2)
- - also orbita ai (but got removed from playstore due to copyright [was too similar to known ios app]) still working link : https://www.taptap.io/app/72457?hreflang=en_US

all apps are safe for user so devs can install them to test and get package names =]

### CODE REVIEW

**Comment by hacknorris-aka-penguin** [comment]
empty here ? :ping_pong: :ping_pong:

**Comment by Donnnno** [comment]
I'll take a look when I have the time!

**Comment by hacknorris-aka-penguin** [comment]
ok.

**Comment by hacknorris-aka-penguin** [comment]
now you have?

**Comment by Donnnno** [comment]
Probably next weekend.

**Comment by hacknorris-aka-penguin** [comment]
wow. too much busy? sorry then

**Comment by Donnnno** [comment]
Yeah, Arcticons is something that I maintain in my spare time, currently I'm very busy with school and work, so I do this mostly in the weekends.

**Comment by hacknorris-aka-penguin** [comment]
oh. its already weekend !!! (now you have time to review?)

**Comment by totoroot** [comment]
@hacknorris-aka-penguin Please consider that this is an Open Source project Donnnno is maintaining in their spare time and that they should not feel obligated to review pull requests just days after you or anyone else has opened them, but only do so when they find the time and have the energy to work on this.
If you have ever maintained software you will know, that working on something over months can be exhausting and even without any additional

**Comment by Donnnno** [comment]
Hi @hacknorris-aka-penguin I have taken a look at your PR! And made some small fixes to Arcticon-ify it a bit:

image

Some feedback for the next time:
- make sure to align everything so that it's centered.
- check if the sizing matches the rest of the pack.
- and make sure to provide them in white.

Overall good work and congrats on your first pull request here!

**Comment by hacknorris-aka-penguin** [comment]
yw!
and yes forgot bout half of these things (yes i was trying to center but idk all features on inkscape) 
size wasnt correct? weird..

**Pull request merged**
