### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MrMatrix1729**
Added 8 apps

- Kalium
- Biome
- Biota
- Jugnoo
- Lobstr
- Natrium
- Panels
- Trust Wallet

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, thanks for your contribution! 

To make them work, you have to add some lines of code to the appfilter.xml file. You can gather it easily with the Icon Request app: 
https://github.com/Kaiserdragon2/IconRequest/releases/tag/v2.0.1

**Comment by Donnnno** [comment]
reminder!

**Comment by MrMatrix1729** [comment]
> reminder!

Sorry for the delay, couldn't wrap my head around and got a little busy. Do I need to update the contributors.xml as well?

**Comment by Donnnno** [comment]
Ah cool, thanks!
>Do I need to update the contributors.xml as well?

Only if you wanna be included in the contributors list in the app :-)

**Comment by Donnnno** [comment]
Feel free to add yourself to the contributors list later, merging the icons now. Nice work! :-)

**Pull request merged**
