### PR TITLE
Added 3 Icons, Updated 1 Icon

### PR DESCRIPTION
**Pull request by Heruvetica**
Added:
- Aldiko Next
- My We
- Prayer Times

and Updated:
- Sofascore

All of the added where in requests.txt so I removed them. I updated appfilter.xml too!
Also, first time contributing so I added myself in contributors.xml
+ I have some questions to ask about future icons I'm planning to make, so where I can contact (or chat with) you?

### CODE REVIEW

**Comment by Donnnno** [comment]
Oh no, something's happening in the appfilter:


18,890 additions, 18,881 deletions

**Comment by Heruvetica** [comment]
Recommitted my changes on the new appfilter and request files (they were updated before checking my pull request). I even added the previous pull request's icons in my fork's /other too.
Is everything okay now?

**Comment by Donnnno** [comment]
Hi! Just checked your icons, and they're good! Just made some small adjustments :-)
I've only had some issues with merging the appfilter, so I'm adding everything in a fresh pull request!

Oh and btw if you wanna chat, we have a Matrix/Element room where we chat about icons here: https://matrix.to/#/#arcticons-central:matrix.org 
You can also contact me personally there: @donno:matrix.org  and otherwise you can always contact me per mail: arcticons@onnno.nl

**Comment by Donnnno** [comment]
I dunno for sure, but a reason I couldn't merge it directly was because there was another PR merged before you that added lines in the appfilter at the exact same location. You can counter this by placing your lines some rows below or up.

**Pull request closed without merging**
