### PR TITLE
Updated appfilter, removed request and added icons

### PR DESCRIPTION
**Pull request by EdwinRodger**
~~No icon .svg icon added~~

### CODE REVIEW

**Comment by EdwinRodger** [comment]
Resolved #1116, #1122 and #1134

I would also like to resolve #1171 but I only have app id for Vi because Samsung Members isn't compatible in my phone 😅

**Comment by dgcampbe** [comment]
Is the issue with Samsung Members that you need the activity name, but can't get it without downloading the app? If so, I can try downloading it onto my old Samsung phone. I assume it is only compatible with Samsung phones for some reason.

**Comment by EdwinRodger** [comment]
> Is the issue with Samsung Members that you need the activity name, but can't get it without downloading the app?

Yes

> If so, I can try downloading it onto my old Samsung phone. 

If you can that will be helpful to me and others. Though it is optional as this problem is of other PR, I am just trying to solve it faster

>I assume it is only compatible with Samsung phones for some reason.

I think that's the issue because I tried search it online and didn't get what I wanted
(I have Xiaomi phone)

**Comment by Donnnno** [comment]
These look very good!

**Pull request merged**
