### PR TITLE
Add 37 new icons and 1 alternative icon and fix 2 icons

### PR DESCRIPTION
**Pull request by wwwwwwari**
This PR:
1. adds 37 new icons - mostly Kemco games and Thai university apps
2. adds an alternative icon for TunnelBear
3. fixes Tungngern and True iService icons (issue details is in #1628)
4. updates appfilter and requests accordingly

### CODE REVIEW

**Comment by Donnnno** [comment]
Woooooowww! that's awesome

**Comment by Donnnno** [comment]
Amazing work, just checked all of them.

Just have two suggestions, but only if you think they're ok:

image

I'm more a fan of trying to stylize those outline-based icons to make them fit more in the pack, but you're the judge on this one! (I have no idea if I fuck things like these up, due to the lack of my understanding of the Thai language 😅 )

**Comment by wwwwwwari** [comment]
They look great! The only thing I think worth mentioning is the third Thai character in the first icon: ษ
I think  in order for it to look like ษ to a Thai the shorter line middle-right of that character needs to be a bit... less slope-y? 
image

The green one is what I mean less slope-y - basically that line needs to be flatter, like - or ~ but not very slope-y like / or \\, if you know what I mean

Just ask me if you have questions 😅

**Comment by Donnnno** [comment]
Cool! So, like this?

image

**Comment by wwwwwwari** [comment]
Yup! That's perfect!

**Pull request merged**
