### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by bragefuglseth**
Added 10 new icons from a request.
	
	<item component="ComponentInfo{pl.allegro/pl.allegro.Allegro}" drawable="allegro" />

	
	<item component="ComponentInfo{com.google.android.tv.remote/com.google.android.tv.remote.RemoteActivity}" drawable="android_tv" />

	
	<item component="ComponentInfo{com.anydo/com.anydo.activity.SplashActivity}" drawable="anydo" />

	
	<item component="ComponentInfo{com.pmp.biblia/com.pmp.biblia.views.activities.SplashScreenActivity_}" drawable="bible" />

	
	<item component="ComponentInfo{pl.infakt.infakt/pl.infakt.infakt.ui.MainActivity}" drawable="infakt" />

	
	<item component="ComponentInfo{pl.inpost.inmobile/pl.inpost.inmobile.presentation.splashscreen.SplashScreenActivity}" drawable="inpost_mobile" />

	
	<item component="ComponentInfo{wit.android.bcpBankingApp.millenniumPL/pl.bankmillennium.gui.prelogin.SplashScreenActivity}" drawable="millennium" />

	
	<item component="ComponentInfo{pl.nask.mobywatel/pl.gov.mc.fringers.mobywatel.MainActivity}" drawable="mobywatel" />

	
	<item component="ComponentInfo{com.sec.android.app.music/com.sec.android.app.music.common.activity.MusicMainActivity}" drawable="samsung_music" />

	
	<item component="ComponentInfo{ninja.sesame.app.edge/ninja.sesame.app.edge.activities.MainActivity}" drawable="sesame" />

### CODE REVIEW

**Comment by Aman9das** [comment]
Are you even human! Great work 🎉

**Comment by Donnnno** [comment]
> 
> 
> Are you even human! Great work 🎉

Probably a dancer 🕺

**Comment by bragefuglseth** [comment]
Just added the icons asked for in issue #473

**Comment by Donnnno** [comment]
Some changes, mostly resizing:

image
image
image

(and removed some doubles) 

Overall, excellent icons, thanks again!

**Pull request merged**
