### PR TITLE
Add: 7 icons #408

### PR DESCRIPTION
**Pull request by Suburbanno**
Group 1

### CODE REVIEW

**Comment by Suburbanno** [comment]
see @Aman9das

**Comment by Aman9das** [comment]
Looks good!

**Comment by Donnnno** [comment]
Great work!

**Comment by Donnnno** [comment]
I've changed some small things about your PR:
- Resized every icon (it didn't have balance, check the contribution guides for that).
- Changed the boxes to the Arcticons default box for consistency.
- Changed the music note to have a single line. 

image

Overall, great work! Thanks :^)

**Comment by Donnnno** [comment]
Oh, and an important thing: Don't save your SVG's in the black or white folders but in the /other folder instead.

**Comment by Suburbanno** [comment]
@Donnnno thanks, sorry for the problems, i'll improve in the next contribution!

**Comment by Donnnno** [comment]
Don't worry! It's your first time :^) Gotta start somewhere, and the icons are good!

**Pull request merged**
